<?php

/**
 * BaseObjectCommentable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $nb_commentaires
 * 
 * @method integer           getNb_commeNtaires() Returns the current record's "nb_commentaires" value
 * @method ObjectCommentable setNb_commeNtaires() Sets the current record's "nb_commentaires" value
 * 
 * @package    senat
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseObjectCommentable extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('object_commentable');
        $this->hasColumn('nb_commentaires', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}