<?php

/**
 * BaseAlinea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $texteloi_id
 * @property integer $article_loi_id
 * @property integer $numero
 * @property string $texte
 * @property string $ref_loi
 * @property ArticleLoi $Article
 * @property Texteloi $Texteloi
 * 
 * @method string     getTexTeloi_id()    Returns the current record's "texteloi_id" value
 * @method integer    getArticle_loi_id() Returns the current record's "article_loi_id" value
 * @method integer    getNumero()         Returns the current record's "numero" value
 * @method string     getTexTe()          Returns the current record's "texte" value
 * @method string     getRef_loi()        Returns the current record's "ref_loi" value
 * @method ArticleLoi getArticle()        Returns the current record's "Article" value
 * @method Texteloi   getTexteloi()       Returns the current record's "Texteloi" value
 * @method Alinea     setTexTeloi_id()    Sets the current record's "texteloi_id" value
 * @method Alinea     setArticle_loi_id() Sets the current record's "article_loi_id" value
 * @method Alinea     setNumero()         Sets the current record's "numero" value
 * @method Alinea     setTexTe()          Sets the current record's "texte" value
 * @method Alinea     setRef_loi()        Sets the current record's "ref_loi" value
 * @method Alinea     setArticle()        Sets the current record's "Article" value
 * @method Alinea     setTexteloi()       Sets the current record's "Texteloi" value
 * 
 * @package    senat
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAlinea extends ObjectCommentable
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('alinea');
        $this->hasColumn('texteloi_id', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('article_loi_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('numero', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('texte', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ref_loi', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));


        $this->index('iarticleloinumero', array(
             'fields' => 
             array(
              0 => 'texteloi_id',
              1 => 'article_loi_id',
              2 => 'numero',
             ),
             'type' => 'unique',
             ));
        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ArticleLoi as Article', array(
             'local' => 'article_loi_id',
             'foreign' => 'id'));

        $this->hasOne('Texteloi', array(
             'local' => 'texteloi_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}