<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePersonnalite extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('personnalite');
        $this->hasColumn('nom', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('nom_de_famille', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('sexe', 'enum', null, array('type' => 'enum', 'values' => array(0 => 'H', 1 => 'F')));
    }

    public function setUp()
    {
        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array('fields' => array(0 => 'nom'), 'unique' => true));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}