<?php

/**
 * BaseAmendement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string                                         $source                                               Type: string(255)
 * @property int                                            $legislature                                          Type: integer
 * @property string                                         $texteloi_id                                          Type: string(16)
 * @property string                                         $numero                                               Type: string(16)
 * @property string                                         $sous_amendement_de                                   Type: string(16)
 * @property int                                            $rectif                                               Type: integer
 * @property string                                         $sujet                                                Type: string(100)
 * @property string                                         $sort                                                 Type: enum, Possible values (INDéFINI, ADOPTé, IRRECEVABLE, REJETé, RETIRé, TOMBE, NON SOUTENU, RETIRé AVANT SéANCE, RECTIFIé, FAVORABLE)
 * @property string                                         $date                                                 Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @property int                                            $auteur_id                                            Type: integer
 * @property string                                         $auteur_groupe_acronyme                               Type: string(16)
 * @property string                                         $signataires                                          Type: string
 * @property string                                         $texte                                                Type: clob
 * @property string                                         $expose                                               Type: clob
 * @property string                                         $content_md5                                          Type: string(36)
 * @property int                                            $nb_multiples                                         Type: integer, default "1"
 * @property Doctrine_Collection|Parlementaire[]            $Parlementaires                                       
 * @property Parlementaire                                  $Auteur                                               
 * @property Texteloi                                       $Texteloi                                             
 * @property Doctrine_Collection|Scrutin[]                  $Scrutins                                             
 * @property Doctrine_Collection|ParlementaireAmendement[]  $ParlementaireAmendements                             
 *  
 * @method string                                           getSource()                                           Type: string(255)
 * @method int                                              getLegislature()                                      Type: integer
 * @method string                                           getTexteloiId()                                       Type: string(16)
 * @method string                                           getNumero()                                           Type: string(16)
 * @method string                                           getSousAmendementDe()                                 Type: string(16)
 * @method int                                              getRectif()                                           Type: integer
 * @method string                                           getSujet()                                            Type: string(100)
 * @method string                                           getSort()                                             Type: enum, Possible values (INDéFINI, ADOPTé, IRRECEVABLE, REJETé, RETIRé, TOMBE, NON SOUTENU, RETIRé AVANT SéANCE, RECTIFIé, FAVORABLE)
 * @method string                                           getDate()                                             Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @method int                                              getAuteurId()                                         Type: integer
 * @method string                                           getAuteurGroupeAcronyme()                             Type: string(16)
 * @method string                                           getSignataires()                                      Type: string
 * @method string                                           getTexte()                                            Type: clob
 * @method string                                           getExpose()                                           Type: clob
 * @method string                                           getContentMd5()                                       Type: string(36)
 * @method int                                              getNbMultiples()                                      Type: integer, default "1"
 * @method Doctrine_Collection|Parlementaire[]              getParlementaires()                                   
 * @method Parlementaire                                    getAuteur()                                           
 * @method Texteloi                                         getTexteloi()                                         
 * @method Doctrine_Collection|Scrutin[]                    getScrutins()                                         
 * @method Doctrine_Collection|ParlementaireAmendement[]    getParlementaireAmendements()                         
 *  
 * @method Amendement                                       setSource(string $val)                                Type: string(255)
 * @method Amendement                                       setLegislature(int $val)                              Type: integer
 * @method Amendement                                       setTexteloiId(string $val)                            Type: string(16)
 * @method Amendement                                       setNumero(string $val)                                Type: string(16)
 * @method Amendement                                       setSousAmendementDe(string $val)                      Type: string(16)
 * @method Amendement                                       setRectif(int $val)                                   Type: integer
 * @method Amendement                                       setSujet(string $val)                                 Type: string(100)
 * @method Amendement                                       setSort(string $val)                                  Type: enum, Possible values (INDéFINI, ADOPTé, IRRECEVABLE, REJETé, RETIRé, TOMBE, NON SOUTENU, RETIRé AVANT SéANCE, RECTIFIé, FAVORABLE)
 * @method Amendement                                       setDate(string $val)                                  Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @method Amendement                                       setAuteurId(int $val)                                 Type: integer
 * @method Amendement                                       setAuteurGroupeAcronyme(string $val)                  Type: string(16)
 * @method Amendement                                       setSignataires(string $val)                           Type: string
 * @method Amendement                                       setTexte(string $val)                                 Type: clob
 * @method Amendement                                       setExpose(string $val)                                Type: clob
 * @method Amendement                                       setContentMd5(string $val)                            Type: string(36)
 * @method Amendement                                       setNbMultiples(int $val)                              Type: integer, default "1"
 * @method Amendement                                       setParlementaires(Doctrine_Collection $val)           
 * @method Amendement                                       setAuteur(Parlementaire $val)                         
 * @method Amendement                                       setTexteloi(Texteloi $val)                            
 * @method Amendement                                       setScrutins(Doctrine_Collection $val)                 
 * @method Amendement                                       setParlementaireAmendements(Doctrine_Collection $val) 
 *  
 * @package    cpc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAmendement extends ObjectCommentable
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('amendement');
        $this->hasColumn('source', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('legislature', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('texteloi_id', 'string', 16, array(
             'type' => 'string',
             'length' => 16,
             ));
        $this->hasColumn('numero', 'string', 16, array(
             'type' => 'string',
             'length' => 16,
             ));
        $this->hasColumn('sous_amendement_de', 'string', 16, array(
             'type' => 'string',
             'length' => 16,
             ));
        $this->hasColumn('rectif', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('sujet', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('sort', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Indéfini',
              1 => 'Adopté',
              2 => 'Irrecevable',
              3 => 'Rejeté',
              4 => 'Retiré',
              5 => 'Tombe',
              6 => 'Non soutenu',
              7 => 'Retiré avant séance',
              8 => 'Rectifié',
              9 => 'Favorable',
             ),
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('auteur_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('auteur_groupe_acronyme', 'string', 16, array(
             'type' => 'string',
             'length' => 16,
             ));
        $this->hasColumn('signataires', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('texte', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('expose', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('content_md5', 'string', 36, array(
             'type' => 'string',
             'length' => 36,
             ));
        $this->hasColumn('nb_multiples', 'integer', null, array(
             'type' => 'integer',
             'default' => 1,
             ));


        $this->index('ft_amendements', array(
             'fields' => 
             array(
              0 => 'sujet',
              1 => 'texte',
              2 => 'expose',
             ),
             'type' => 'fulltext',
             ));
        $this->index('uniq_loi_num', array(
             'fields' => 
             array(
              0 => 'legislature',
              1 => 'texteloi_id',
              2 => 'numero',
              3 => 'rectif',
             ),
             'type' => 'unique',
             ));
        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Parlementaire as Parlementaires', array(
             'refClass' => 'ParlementaireAmendement',
             'local' => 'amendement_id',
             'foreign' => 'parlementaire_id'));

        $this->hasOne('Parlementaire as Auteur', array(
             'local' => 'auteur_id',
             'foreign' => 'id'));

        $this->hasOne('Texteloi', array(
             'local' => 'texteloi_id',
             'foreign' => 'id'));

        $this->hasMany('Scrutin as Scrutins', array(
             'local' => 'id',
             'foreign' => 'amendement_id'));

        $this->hasMany('ParlementaireAmendement as ParlementaireAmendements', array(
             'local' => 'id',
             'foreign' => 'amendement_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $taggable0 = new Taggable();
        $solrable0 = new Solrable(array(
             'title' => 
             array(
              0 => 'titre',
             ),
             'description' => 
             array(
              0 => 'expose',
              1 => 'texte',
              2 => 'signataires',
             ),
             'moretags' => 
             array(
              0 => 'Parlementaires',
              1 => 'sort',
              2 => 'dossier',
              3 => 'link_source',
             ),
             'date' => 'date',
             'index_if' => 'is_last_version',
             ));
        $this->actAs($timestampable0);
        $this->actAs($taggable0);
        $this->actAs($solrable0);
    }
}