<?php

/**
 * BaseArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $titre
 * @property string $corps
 * @property string $user_corps
 * @property string $categorie
 * @property integer $citoyen_id
 * @property integer $article_id
 * @property string $link
 * @property enum $status
 * @property integer $object_id
 * @property Citoyen $Citoyen
 * @property Article $Article
 * @property Doctrine_Collection $SousArticles
 * 
 * @method string              getTiTre()        Returns the current record's "titre" value
 * @method string              getCorps()        Returns the current record's "corps" value
 * @method string              getUser_corps()   Returns the current record's "user_corps" value
 * @method string              getCategorie()    Returns the current record's "categorie" value
 * @method integer             getCitoyen_id()   Returns the current record's "citoyen_id" value
 * @method integer             getArticle_id()   Returns the current record's "article_id" value
 * @method string              getLink()         Returns the current record's "link" value
 * @method enum                getStatuS()       Returns the current record's "status" value
 * @method integer             getObject_id()    Returns the current record's "object_id" value
 * @method Citoyen             getCitoyen()      Returns the current record's "Citoyen" value
 * @method Article             getArticle()      Returns the current record's "Article" value
 * @method Doctrine_Collection getSousArticles() Returns the current record's "SousArticles" collection
 * @method Article             setTiTre()        Sets the current record's "titre" value
 * @method Article             setCorps()        Sets the current record's "corps" value
 * @method Article             setUser_corps()   Sets the current record's "user_corps" value
 * @method Article             setCategorie()    Sets the current record's "categorie" value
 * @method Article             setCitoyen_id()   Sets the current record's "citoyen_id" value
 * @method Article             setArticle_id()   Sets the current record's "article_id" value
 * @method Article             setLink()         Sets the current record's "link" value
 * @method Article             setStatuS()       Sets the current record's "status" value
 * @method Article             setObject_id()    Sets the current record's "object_id" value
 * @method Article             setCitoyen()      Sets the current record's "Citoyen" value
 * @method Article             setArticle()      Sets the current record's "Article" value
 * @method Article             setSousArticles() Sets the current record's "SousArticles" collection
 * 
 * @package    senat
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArticle extends ObjectCommentable
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('article');
        $this->hasColumn('titre', 'string', 254, array(
             'type' => 'string',
             'length' => 254,
             ));
        $this->hasColumn('corps', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('user_corps', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('categorie', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('citoyen_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('article_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('link', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'public',
              1 => 'brouillon',
              2 => 'offline',
             ),
             'default' => 'brouillon',
             ));
        $this->hasColumn('object_id', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->index('icategories', array(
             'fields' => 
             array(
              0 => 'categorie',
             ),
             ));
        $this->index('iobject', array(
             'fields' => 
             array(
              0 => 'categorie',
              1 => 'object_id',
             ),
             'unique' => true,
             ));
        $this->index('ititre', array(
             'fields' => 
             array(
              0 => 'categorie',
              1 => 'titre(200)',
             ),
             ));
        $this->index('ititrecitoyen', array(
             'fields' => 
             array(
              0 => 'categorie',
              1 => 'titre(200)',
              2 => 'citoyen_id',
             ),
             ));
        $this->index('iarticle', array(
             'fields' => 
             array(
              0 => 'article_id',
             ),
             ));
        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Citoyen', array(
             'local' => 'citoyen_id',
             'foreign' => 'id'));

        $this->hasOne('Article', array(
             'local' => 'article_id',
             'foreign' => 'id'));

        $this->hasMany('Article as SousArticles', array(
             'local' => 'id',
             'foreign' => 'article_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $versionable0 = new Doctrine_Template_Versionable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'titre',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($versionable0);
        $this->actAs($sluggable0);
    }
}