<?php

/**
 * BaseCommentaire
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $citoyen_id
 * @property string $commentaire
 * @property boolean $is_public
 * @property string $ip_address
 * @property integer $rate
 * @property string $object_type
 * @property string $object_id
 * @property string $lien
 * @property string $presentation
 * @property Citoyen $Citoyen
 * @property Doctrine_Collection $Objects
 * 
 * @method integer             getCitoyen_id()   Returns the current record's "citoyen_id" value
 * @method string              getCommentaire()  Returns the current record's "commentaire" value
 * @method boolean             getIs_publIc()    Returns the current record's "is_public" value
 * @method string              getIp_address()   Returns the current record's "ip_address" value
 * @method integer             getRate()         Returns the current record's "rate" value
 * @method string              getObject_type()  Returns the current record's "object_type" value
 * @method string              getObject_id()    Returns the current record's "object_id" value
 * @method string              getLien()         Returns the current record's "lien" value
 * @method string              getPresentation() Returns the current record's "presentation" value
 * @method Citoyen             getCitoyen()      Returns the current record's "Citoyen" value
 * @method Doctrine_Collection getObjects()      Returns the current record's "Objects" collection
 * @method Commentaire         setCitoyen_id()   Sets the current record's "citoyen_id" value
 * @method Commentaire         setCommentaire()  Sets the current record's "commentaire" value
 * @method Commentaire         setIs_publIc()    Sets the current record's "is_public" value
 * @method Commentaire         setIp_address()   Sets the current record's "ip_address" value
 * @method Commentaire         setRate()         Sets the current record's "rate" value
 * @method Commentaire         setObject_type()  Sets the current record's "object_type" value
 * @method Commentaire         setObject_id()    Sets the current record's "object_id" value
 * @method Commentaire         setLien()         Sets the current record's "lien" value
 * @method Commentaire         setPresentation() Sets the current record's "presentation" value
 * @method Commentaire         setCitoyen()      Sets the current record's "Citoyen" value
 * @method Commentaire         setObjects()      Sets the current record's "Objects" collection
 * 
 * @package    senat
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCommentaire extends ObjectRated
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('commentaire');
        $this->hasColumn('citoyen_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('commentaire', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('is_public', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('ip_address', 'string', 512, array(
             'type' => 'string',
             'length' => 512,
             ));
        $this->hasColumn('rate', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('object_type', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('object_id', 'string', 16, array(
             'type' => 'string',
             'length' => 16,
             ));
        $this->hasColumn('lien', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('presentation', 'string', 512, array(
             'type' => 'string',
             'length' => 512,
             ));


        $this->index('commentable', array(
             'fields' => 
             array(
              0 => 'object_type',
              1 => 'object_id',
             ),
             ));
        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Citoyen', array(
             'local' => 'citoyen_id',
             'foreign' => 'id'));

        $this->hasMany('CommentaireObject as Objects', array(
             'local' => 'id',
             'foreign' => 'commentaire_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $solrable0 = new Solrable(array(
             'title' => 
             array(
              0 => 'presentation',
             ),
             'description' => 
             array(
              0 => 'Citoyen',
              1 => 'commentaire',
             ),
             'moretags' => 
             array(
              0 => 'Citoyen',
              1 => 'object_type',
              2 => 'object_id',
              3 => 'Parlementaires',
             ),
             'date' => 'created_at',
             'index_if' => 'is_public',
             ));
        $this->actAs($timestampable0);
        $this->actAs($solrable0);
    }
}