<?php

/**
 * BaseTexteloi
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string                                       $id                                                 Type: string(16), unique
 * @property int                                          $legislature                                        Type: integer
 * @property int                                          $numero                                             Type: integer
 * @property string                                       $annexe                                             Type: string(12)
 * @property string                                       $type                                               Type: enum, Possible values (PROPOSITION DE LOI, PROPOSITION DE RéSOLUTION, PROJET DE LOI, TEXTE DE LA COMMISSION, LETTRE, RAPPORT, RAPPORT D'INFORMATION, AVIS)
 * @property string                                       $type_details                                       Type: string(512)
 * @property string                                       $categorie                                          Type: string(128)
 * @property string                                       $id_dossier_an                                      Type: string(255)
 * @property string                                       $titre                                              Type: string(512)
 * @property string                                       $date                                               Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @property string                                       $source                                             Type: string(128), unique
 * @property int                                          $organisme_id                                       Type: integer
 * @property string                                       $signataires                                        Type: string
 * @property string                                       $contenu                                            Type: string
 * @property Doctrine_Collection|Parlementaire[]          $Parlementaires                                     
 * @property Organisme                                    $Organisme                                          
 * @property Doctrine_Collection|Scrutin[]                $Scrutins                                           
 * @property Doctrine_Collection|Amendement[]             $Amendements                                        
 * @property Doctrine_Collection|ArticleLoi[]             $ArticleLois                                        
 * @property Doctrine_Collection|Alinea[]                 $Alineas                                            
 * @property Doctrine_Collection|TitreLoi[]               $TitreLois                                          
 * @property Doctrine_Collection|ParlementaireTexteloi[]  $ParlementaireTextelois                             
 *  
 * @method string                                         getId()                                             Type: string(16), unique
 * @method int                                            getLegislature()                                    Type: integer
 * @method int                                            getNumero()                                         Type: integer
 * @method string                                         getAnnexe()                                         Type: string(12)
 * @method string                                         getType()                                           Type: enum, Possible values (PROPOSITION DE LOI, PROPOSITION DE RéSOLUTION, PROJET DE LOI, TEXTE DE LA COMMISSION, LETTRE, RAPPORT, RAPPORT D'INFORMATION, AVIS)
 * @method string                                         getTypeDetails()                                    Type: string(512)
 * @method string                                         getCategorie()                                      Type: string(128)
 * @method string                                         getIdDossierAn()                                    Type: string(255)
 * @method string                                         getTitre()                                          Type: string(512)
 * @method string                                         getDate()                                           Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @method string                                         getSource()                                         Type: string(128), unique
 * @method int                                            getOrganismeId()                                    Type: integer
 * @method string                                         getSignataires()                                    Type: string
 * @method string                                         getContenu()                                        Type: string
 * @method Doctrine_Collection|Parlementaire[]            getParlementaires()                                 
 * @method Organisme                                      getOrganisme()                                      
 * @method Doctrine_Collection|Scrutin[]                  getScrutins()                                       
 * @method Doctrine_Collection|Amendement[]               getAmendements()                                    
 * @method Doctrine_Collection|ArticleLoi[]               getArticleLois()                                    
 * @method Doctrine_Collection|Alinea[]                   getAlineas()                                        
 * @method Doctrine_Collection|TitreLoi[]                 getTitreLois()                                      
 * @method Doctrine_Collection|ParlementaireTexteloi[]    getParlementaireTextelois()                         
 *  
 * @method Texteloi                                       setId(string $val)                                  Type: string(16), unique
 * @method Texteloi                                       setLegislature(int $val)                            Type: integer
 * @method Texteloi                                       setNumero(int $val)                                 Type: integer
 * @method Texteloi                                       setAnnexe(string $val)                              Type: string(12)
 * @method Texteloi                                       setType(string $val)                                Type: enum, Possible values (PROPOSITION DE LOI, PROPOSITION DE RéSOLUTION, PROJET DE LOI, TEXTE DE LA COMMISSION, LETTRE, RAPPORT, RAPPORT D'INFORMATION, AVIS)
 * @method Texteloi                                       setTypeDetails(string $val)                         Type: string(512)
 * @method Texteloi                                       setCategorie(string $val)                           Type: string(128)
 * @method Texteloi                                       setIdDossierAn(string $val)                         Type: string(255)
 * @method Texteloi                                       setTitre(string $val)                               Type: string(512)
 * @method Texteloi                                       setDate(string $val)                                Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @method Texteloi                                       setSource(string $val)                              Type: string(128), unique
 * @method Texteloi                                       setOrganismeId(int $val)                            Type: integer
 * @method Texteloi                                       setSignataires(string $val)                         Type: string
 * @method Texteloi                                       setContenu(string $val)                             Type: string
 * @method Texteloi                                       setParlementaires(Doctrine_Collection $val)         
 * @method Texteloi                                       setOrganisme(Organisme $val)                        
 * @method Texteloi                                       setScrutins(Doctrine_Collection $val)               
 * @method Texteloi                                       setAmendements(Doctrine_Collection $val)            
 * @method Texteloi                                       setArticleLois(Doctrine_Collection $val)            
 * @method Texteloi                                       setAlineas(Doctrine_Collection $val)                
 * @method Texteloi                                       setTitreLois(Doctrine_Collection $val)              
 * @method Texteloi                                       setParlementaireTextelois(Doctrine_Collection $val) 
 *  
 * @package    cpc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTexteloi extends ObjectCommentable
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('texteloi');
        $this->hasColumn('id', 'string', 16, array(
             'type' => 'string',
             'unique' => true,
             'length' => 16,
             ));
        $this->hasColumn('legislature', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('numero', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('annexe', 'string', 12, array(
             'type' => 'string',
             'length' => 12,
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Proposition de loi',
              1 => 'Proposition de résolution',
              2 => 'Projet de loi',
              3 => 'Texte de la commission',
              4 => 'Lettre',
              5 => 'Rapport',
              6 => 'Rapport d\'information',
              7 => 'Avis',
             ),
             ));
        $this->hasColumn('type_details', 'string', 512, array(
             'type' => 'string',
             'length' => 512,
             ));
        $this->hasColumn('categorie', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('id_dossier_an', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('titre', 'string', 512, array(
             'type' => 'string',
             'length' => 512,
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('source', 'string', 128, array(
             'type' => 'string',
             'unique' => true,
             'length' => 128,
             ));
        $this->hasColumn('organisme_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('signataires', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('contenu', 'string', null, array(
             'type' => 'string',
             ));


        $this->index('index_url', array(
             'fields' => 
             array(
              0 => 'id_dossier_an',
             ),
             ));
        $this->index('index_alpha', array(
             'fields' => 
             array(
              0 => 'numero',
              1 => 'annexe',
             ),
             'type' => 'unique',
             ));
        $this->index('index_type', array(
             'fields' => 
             array(
              0 => 'type(30)',
              1 => 'type_details(200)',
             ),
             ));
        $this->index('index_date', array(
             'fields' => 
             array(
              0 => 'date',
             ),
             ));
        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Parlementaire as Parlementaires', array(
             'refClass' => 'ParlementaireTexteloi',
             'local' => 'texteloi_id',
             'foreign' => 'parlementaire_id'));

        $this->hasOne('Organisme', array(
             'local' => 'organisme_id',
             'foreign' => 'id'));

        $this->hasMany('Scrutin as Scrutins', array(
             'local' => 'id',
             'foreign' => 'texteloi_id'));

        $this->hasMany('Amendement as Amendements', array(
             'local' => 'id',
             'foreign' => 'texteloi_id'));

        $this->hasMany('ArticleLoi as ArticleLois', array(
             'local' => 'id',
             'foreign' => 'texteloi_id'));

        $this->hasMany('Alinea as Alineas', array(
             'local' => 'id',
             'foreign' => 'texteloi_id'));

        $this->hasMany('TitreLoi as TitreLois', array(
             'local' => 'id',
             'foreign' => 'texteloi_id'));

        $this->hasMany('ParlementaireTexteloi as ParlementaireTextelois', array(
             'local' => 'id',
             'foreign' => 'texteloi_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $taggable0 = new Taggable();
        $solrable0 = new Solrable(array(
             'title' => 
             array(
              0 => 'titre',
             ),
             'description' => 
             array(
              0 => 'contenu',
              1 => 'id',
             ),
             'moretags' => 
             array(
              0 => 'categorie',
              1 => 'type',
              2 => 'Organisme',
              3 => 'Parlementaires',
              4 => 'nature',
              5 => 'dossier',
              6 => 'link_source',
             ),
             'date' => 'date',
             ));
        $this->actAs($timestampable0);
        $this->actAs($taggable0);
        $this->actAs($solrable0);
    }
}