<?php

/**
 * BaseSection
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $md5
 * @property string $titre
 * @property string $titre_complet
 * @property integer $section_id
 * @property string $min_date
 * @property date $max_date
 * @property integer $timestamp
 * @property integer $nb_interventions
 * @property string $id_dossier_institution
 * @property Section $Section
 * @property Doctrine_Collection $SubSections
 * @property Doctrine_Collection $Interventions
 * 
 * @method string              getMd5()                    Returns the current record's "md5" value
 * @method string              getTiTre()                  Returns the current record's "titre" value
 * @method string              getTiTre_compleT()          Returns the current record's "titre_complet" value
 * @method integer             getSection_id()             Returns the current record's "section_id" value
 * @method string              getMin_date()               Returns the current record's "min_date" value
 * @method date                getMax_date()               Returns the current record's "max_date" value
 * @method integer             getTimesTamp()              Returns the current record's "timestamp" value
 * @method integer             getNb_iNterveNtioNs()       Returns the current record's "nb_interventions" value
 * @method string              getId_dossIer_InstItutIon() Returns the current record's "id_dossier_institution" value
 * @method Section             getSection()                Returns the current record's "Section" value
 * @method Doctrine_Collection getSubSections()            Returns the current record's "SubSections" collection
 * @method Doctrine_Collection getInterventions()          Returns the current record's "Interventions" collection
 * @method Section             setMd5()                    Sets the current record's "md5" value
 * @method Section             setTiTre()                  Sets the current record's "titre" value
 * @method Section             setTiTre_compleT()          Sets the current record's "titre_complet" value
 * @method Section             setSection_id()             Sets the current record's "section_id" value
 * @method Section             setMin_date()               Sets the current record's "min_date" value
 * @method Section             setMax_date()               Sets the current record's "max_date" value
 * @method Section             setTimesTamp()              Sets the current record's "timestamp" value
 * @method Section             setNb_iNterveNtioNs()       Sets the current record's "nb_interventions" value
 * @method Section             setId_dossIer_InstItutIon() Sets the current record's "id_dossier_institution" value
 * @method Section             setSection()                Sets the current record's "Section" value
 * @method Section             setSubSections()            Sets the current record's "SubSections" collection
 * @method Section             setInterventions()          Sets the current record's "Interventions" collection
 * 
 * @package    senat
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSection extends ObjectCommentable
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('section');
        $this->hasColumn('md5', 'string', 36, array(
             'type' => 'string',
             'unique' => true,
             'length' => 36,
             ));
        $this->hasColumn('titre', 'string', 256, array(
             'type' => 'string',
             'length' => 256,
             ));
        $this->hasColumn('titre_complet', 'string', 512, array(
             'type' => 'string',
             'length' => 512,
             ));
        $this->hasColumn('section_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('min_date', 'string', 15, array(
             'type' => 'string',
             'length' => 15,
             ));
        $this->hasColumn('max_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('timestamp', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('nb_interventions', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('id_dossier_institution', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Section', array(
             'local' => 'section_id',
             'foreign' => 'id'));

        $this->hasMany('Section as SubSections', array(
             'local' => 'id',
             'foreign' => 'section_id'));

        $this->hasMany('Intervention as Interventions', array(
             'local' => 'id',
             'foreign' => 'section_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $taggable0 = new Taggable();
        $solrable0 = new Solrable(array(
             'title' => 
             array(
              0 => 'titre_complet',
             ),
             'extra_weight' => 1.3,
             'index_if' => 'is_parent',
             'date' => 'max_date',
             ));
        $this->actAs($timestampable0);
        $this->actAs($taggable0);
        $this->actAs($solrable0);
    }
}