<?php

/**
 * BasePersonnalite
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nom
 * @property string $nom_de_famille
 * @property enum $sexe
 * @property date $date_naissance
 * @property Doctrine_Collection $Interventions
 * 
 * @method string              getNom()            Returns the current record's "nom" value
 * @method string              getNom_de_famille() Returns the current record's "nom_de_famille" value
 * @method enum                getSexe()           Returns the current record's "sexe" value
 * @method date                getDate_naissance() Returns the current record's "date_naissance" value
 * @method Doctrine_Collection getInterventions()  Returns the current record's "Interventions" collection
 * @method Personnalite        setNom()            Sets the current record's "nom" value
 * @method Personnalite        setNom_de_famille() Sets the current record's "nom_de_famille" value
 * @method Personnalite        setSexe()           Sets the current record's "sexe" value
 * @method Personnalite        setDate_naissance() Sets the current record's "date_naissance" value
 * @method Personnalite        setInterventions()  Sets the current record's "Interventions" collection
 * 
 * @package    senat
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePersonnalite extends ObjectCommentable
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('personnalite');
        $this->hasColumn('nom', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('nom_de_famille', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('sexe', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'H',
              1 => 'F',
             ),
             ));
        $this->hasColumn('date_naissance', 'date', null, array(
             'type' => 'date',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Intervention as Interventions', array(
             'local' => 'id',
             'foreign' => 'personnalite_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'nom_clean_for_slug',
             ),
             'unique' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}