<?php

/**
 * BasePresence
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                                   $parlementaire_id                           Type: integer
 * @property string                                $parlementaire_groupe_acronyme              Type: string(16)
 * @property int                                   $seance_id                                  Type: integer
 * @property int                                   $nb_preuves                                 Type: integer
 * @property string                                $date                                       Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @property Parlementaire                         $Parlementaire                              
 * @property Seance                                $Seance                                     
 * @property Doctrine_Collection|PreuvePresence[]  $Preuves                                    
 *  
 * @method int                                     getParlementaireId()                        Type: integer
 * @method string                                  getParlementaireGroupeAcronyme()            Type: string(16)
 * @method int                                     getSeanceId()                               Type: integer
 * @method int                                     getNbPreuves()                              Type: integer
 * @method string                                  getDate()                                   Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @method Parlementaire                           getParlementaire()                          
 * @method Seance                                  getSeance()                                 
 * @method Doctrine_Collection|PreuvePresence[]    getPreuves()                                
 *  
 * @method Presence                                setParlementaireId(int $val)                Type: integer
 * @method Presence                                setParlementaireGroupeAcronyme(string $val) Type: string(16)
 * @method Presence                                setSeanceId(int $val)                       Type: integer
 * @method Presence                                setNbPreuves(int $val)                      Type: integer
 * @method Presence                                setDate(string $val)                        Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @method Presence                                setParlementaire(Parlementaire $val)        
 * @method Presence                                setSeance(Seance $val)                      
 * @method Presence                                setPreuves(Doctrine_Collection $val)        
 *  
 * @package    cpc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePresence extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('presence');
        $this->hasColumn('parlementaire_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('parlementaire_groupe_acronyme', 'string', 16, array(
             'type' => 'string',
             'length' => 16,
             ));
        $this->hasColumn('seance_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('nb_preuves', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Parlementaire', array(
             'local' => 'parlementaire_id',
             'foreign' => 'id'));

        $this->hasOne('Seance', array(
             'local' => 'seance_id',
             'foreign' => 'id'));

        $this->hasMany('PreuvePresence as Preuves', array(
             'local' => 'id',
             'foreign' => 'presence_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}