<?php

/**
 * BaseParlementaireAmendement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $parlementaire_id
 * @property string $amendement_id
 * @property integer $numero_signataire
 * @property Parlementaire $Parlementaire
 * @property Amendement $Amendement
 * 
 * @method integer                 getParlementaire_id()  Returns the current record's "parlementaire_id" value
 * @method string                  getAmendement_id()     Returns the current record's "amendement_id" value
 * @method integer                 getNumero_sigNataire() Returns the current record's "numero_signataire" value
 * @method Parlementaire           getParlementaire()     Returns the current record's "Parlementaire" value
 * @method Amendement              getAmendement()        Returns the current record's "Amendement" value
 * @method ParlementaireAmendement setParlementaire_id()  Sets the current record's "parlementaire_id" value
 * @method ParlementaireAmendement setAmendement_id()     Sets the current record's "amendement_id" value
 * @method ParlementaireAmendement setNumero_sigNataire() Sets the current record's "numero_signataire" value
 * @method ParlementaireAmendement setParlementaire()     Sets the current record's "Parlementaire" value
 * @method ParlementaireAmendement setAmendement()        Sets the current record's "Amendement" value
 * 
 * @package    senat
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseParlementaireAmendement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('parlementaire_amendement');
        $this->hasColumn('parlementaire_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('amendement_id', 'string', 36, array(
             'type' => 'string',
             'length' => 36,
             ));
        $this->hasColumn('numero_signataire', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Parlementaire', array(
             'local' => 'parlementaire_id',
             'foreign' => 'id'));

        $this->hasOne('Amendement', array(
             'local' => 'amendement_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}