<?php

/**
 * BaseIntervention
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int            $nb_mots                                    Type: integer
 * @property string         $md5                                        Type: string(36), unique
 * @property string         $intervention                               Type: string
 * @property int            $timestamp                                  Type: integer
 * @property string         $source                                     Type: string(128)
 * @property int            $seance_id                                  Type: integer
 * @property int            $section_id                                 Type: integer
 * @property string         $type                                       Type: enum, Possible values (COMMISSION, QUESTION, LOI)
 * @property string         $date                                       Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @property int            $personnalite_id                            Type: integer
 * @property int            $parlementaire_id                           Type: integer
 * @property string         $parlementaire_groupe_acronyme              Type: string(16)
 * @property string         $fonction                                   Type: string(512)
 * @property Section        $Section                                    
 * @property Seance         $Seance                                     
 * @property Personnalite   $Personnalite                               
 * @property Parlementaire  $Parlementaire                              
 *  
 * @method int              getNbMots()                                 Type: integer
 * @method string           getMd5()                                    Type: string(36), unique
 * @method string           getIntervention()                           Type: string
 * @method int              getTimestamp()                              Type: integer
 * @method string           getSource()                                 Type: string(128)
 * @method int              getSeanceId()                               Type: integer
 * @method int              getSectionId()                              Type: integer
 * @method string           getType()                                   Type: enum, Possible values (COMMISSION, QUESTION, LOI)
 * @method string           getDate()                                   Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @method int              getPersonnaliteId()                         Type: integer
 * @method int              getParlementaireId()                        Type: integer
 * @method string           getParlementaireGroupeAcronyme()            Type: string(16)
 * @method string           getFonction()                               Type: string(512)
 * @method Section          getSection()                                
 * @method Seance           getSeance()                                 
 * @method Personnalite     getPersonnalite()                           
 * @method Parlementaire    getParlementaire()                          
 *  
 * @method Intervention     setNbMots(int $val)                         Type: integer
 * @method Intervention     setMd5(string $val)                         Type: string(36), unique
 * @method Intervention     setIntervention(string $val)                Type: string
 * @method Intervention     setTimestamp(int $val)                      Type: integer
 * @method Intervention     setSource(string $val)                      Type: string(128)
 * @method Intervention     setSeanceId(int $val)                       Type: integer
 * @method Intervention     setSectionId(int $val)                      Type: integer
 * @method Intervention     setType(string $val)                        Type: enum, Possible values (COMMISSION, QUESTION, LOI)
 * @method Intervention     setDate(string $val)                        Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @method Intervention     setPersonnaliteId(int $val)                 Type: integer
 * @method Intervention     setParlementaireId(int $val)                Type: integer
 * @method Intervention     setParlementaireGroupeAcronyme(string $val) Type: string(16)
 * @method Intervention     setFonction(string $val)                    Type: string(512)
 * @method Intervention     setSection(Section $val)                    
 * @method Intervention     setSeance(Seance $val)                      
 * @method Intervention     setPersonnalite(Personnalite $val)          
 * @method Intervention     setParlementaire(Parlementaire $val)        
 *  
 * @package    cpc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIntervention extends ObjectCommentable
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('intervention');
        $this->hasColumn('nb_mots', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('md5', 'string', 36, array(
             'type' => 'string',
             'unique' => true,
             'length' => 36,
             ));
        $this->hasColumn('intervention', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('timestamp', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('source', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('seance_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('section_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'commission',
              1 => 'question',
              2 => 'loi',
             ),
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('personnalite_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('parlementaire_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('parlementaire_groupe_acronyme', 'string', 16, array(
             'type' => 'string',
             'length' => 16,
             ));
        $this->hasColumn('fonction', 'string', 512, array(
             'type' => 'string',
             'length' => 512,
             ));


        $this->index('date_intervention', array(
             'fields' => 
             array(
              0 => 'date',
             ),
             ));
        $this->index('ft_intervention', array(
             'fields' => 
             array(
              0 => 'intervention',
             ),
             'type' => 'fulltext',
             ));
        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Section', array(
             'local' => 'section_id',
             'foreign' => 'id'));

        $this->hasOne('Seance', array(
             'local' => 'seance_id',
             'foreign' => 'id'));

        $this->hasOne('Personnalite', array(
             'local' => 'personnalite_id',
             'foreign' => 'id'));

        $this->hasOne('Parlementaire', array(
             'local' => 'parlementaire_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $taggable0 = new Taggable();
        $solrable0 = new Solrable(array(
             'description' => 
             array(
              0 => 'Parlementaire',
              1 => 'Personnalite',
              2 => 'intervention',
             ),
             'moretags' => 
             array(
              0 => 'Parlementaire',
              1 => 'Personnalite',
              2 => 'type',
              3 => 'dossier',
              4 => 'organisme',
              5 => 'link_source',
             ),
             'devaluate_if_wordcount_under' => 200,
             'date' => 'full_date',
             ));
        $this->actAs($timestampable0);
        $this->actAs($taggable0);
        $this->actAs($solrable0);
    }
}