<?php

/**
 * BaseCommentaireObject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string             $object_type                     Type: string(64)
 * @property int                $object_id                       Type: integer
 * @property int                $commentaire_id                  Type: integer
 * @property Commentaire        $Commentaire                     
 *  
 * @method string               getObjectType()                  Type: string(64)
 * @method int                  getObjectId()                    Type: integer
 * @method int                  getCommentaireId()               Type: integer
 * @method Commentaire          getCommentaire()                 
 *  
 * @method CommentaireObject    setObjectType(string $val)       Type: string(64)
 * @method CommentaireObject    setObjectId(int $val)            Type: integer
 * @method CommentaireObject    setCommentaireId(int $val)       Type: integer
 * @method CommentaireObject    setCommentaire(Commentaire $val) 
 *  
 * @package    cpc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCommentaireObject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('commentaire_object');
        $this->hasColumn('object_type', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('object_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('commentaire_id', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->index('unique', array(
             'fields' => 
             array(
              0 => 'object_type',
              1 => 'object_id',
              2 => 'commentaire_id',
             ),
             'type' => 'unique',
             ));
        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Commentaire', array(
             'local' => 'commentaire_id',
             'foreign' => 'id'));
    }
}