<?php

/**
 * BaseRate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $object_type
 * @property integer $object_id
 * @property integer $rate
 * @property integer $citoyen_id
 * @property Citoyen $Citoyen
 * 
 * @method string  getObject_type() Returns the current record's "object_type" value
 * @method integer getObject_id()   Returns the current record's "object_id" value
 * @method integer getRate()        Returns the current record's "rate" value
 * @method integer getCitoyen_id()  Returns the current record's "citoyen_id" value
 * @method Citoyen getCitoyen()     Returns the current record's "Citoyen" value
 * @method Rate    setObject_type() Sets the current record's "object_type" value
 * @method Rate    setObject_id()   Sets the current record's "object_id" value
 * @method Rate    setRate()        Sets the current record's "rate" value
 * @method Rate    setCitoyen_id()  Sets the current record's "citoyen_id" value
 * @method Rate    setCitoyen()     Sets the current record's "Citoyen" value
 * 
 * @package    senat
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rate');
        $this->hasColumn('object_type', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('object_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('rate', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('citoyen_id', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->index('unique', array(
             'fields' => 
             array(
              0 => 'object_type',
              1 => 'object_id',
              2 => 'citoyen_id',
             ),
             'type' => 'unique',
             ));
        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Citoyen', array(
             'local' => 'citoyen_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}