<?php

/**
 * BaseParlementaireOrganisme
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $fonction
 * @property integer $importance
 * @property date $debut_fonction
 * @property integer $organisme_id
 * @property integer $parlementaire_id
 * @property Parlementaire $Parlementaire
 * @property Organisme $Organisme
 * 
 * @method string                 getFonction()         Returns the current record's "fonction" value
 * @method integer                getImportance()       Returns the current record's "importance" value
 * @method date                   getDebut_fonction()   Returns the current record's "debut_fonction" value
 * @method integer                getOrganisme_id()     Returns the current record's "organisme_id" value
 * @method integer                getParlementaire_id() Returns the current record's "parlementaire_id" value
 * @method Parlementaire          getParlementaire()    Returns the current record's "Parlementaire" value
 * @method Organisme              getOrganisme()        Returns the current record's "Organisme" value
 * @method ParlementaireOrganisme setFonction()         Sets the current record's "fonction" value
 * @method ParlementaireOrganisme setImportance()       Sets the current record's "importance" value
 * @method ParlementaireOrganisme setDebut_fonction()   Sets the current record's "debut_fonction" value
 * @method ParlementaireOrganisme setOrganisme_id()     Sets the current record's "organisme_id" value
 * @method ParlementaireOrganisme setParlementaire_id() Sets the current record's "parlementaire_id" value
 * @method ParlementaireOrganisme setParlementaire()    Sets the current record's "Parlementaire" value
 * @method ParlementaireOrganisme setOrganisme()        Sets the current record's "Organisme" value
 * 
 * @package    senat
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseParlementaireOrganisme extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('parlementaire_organisme');
        $this->hasColumn('fonction', 'string', 512, array(
             'type' => 'string',
             'length' => 512,
             ));
        $this->hasColumn('importance', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('debut_fonction', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('organisme_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('parlementaire_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Parlementaire', array(
             'local' => 'parlementaire_id',
             'foreign' => 'id'));

        $this->hasOne('Organisme', array(
             'local' => 'organisme_id',
             'foreign' => 'id'));
    }
}