<?php

/**
 * BaseTitreLoi
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $texteloi_id
 * @property string $chapitre
 * @property string $section
 * @property string $titre
 * @property string $expose
 * @property integer $parlementaire_id
 * @property date $date
 * @property string $source
 * @property integer $nb_articles
 * @property integer $titre_loi_id
 * @property Parlementaire $Parlementaire
 * @property TitreLoi $TitreLoi
 * @property Texteloi $Texteloi
 * @property Doctrine_Collection $Articles
 * @property Doctrine_Collection $SousSections
 * 
 * @method string              getTexTeloi_id()      Returns the current record's "texteloi_id" value
 * @method string              getChapitre()         Returns the current record's "chapitre" value
 * @method string              getSection()          Returns the current record's "section" value
 * @method string              getTiTre()            Returns the current record's "titre" value
 * @method string              getExposE()           Returns the current record's "expose" value
 * @method integer             getParlementaire_id() Returns the current record's "parlementaire_id" value
 * @method date                getDate()             Returns the current record's "date" value
 * @method string              getSource()           Returns the current record's "source" value
 * @method integer             getNb_articles()      Returns the current record's "nb_articles" value
 * @method integer             getTiTre_loi_id()     Returns the current record's "titre_loi_id" value
 * @method Parlementaire       getParlementaire()    Returns the current record's "Parlementaire" value
 * @method TitreLoi            getTitreLoi()         Returns the current record's "TitreLoi" value
 * @method Texteloi            getTexteloi()         Returns the current record's "Texteloi" value
 * @method Doctrine_Collection getArticles()         Returns the current record's "Articles" collection
 * @method Doctrine_Collection getSousSections()     Returns the current record's "SousSections" collection
 * @method TitreLoi            setTexTeloi_id()      Sets the current record's "texteloi_id" value
 * @method TitreLoi            setChapitre()         Sets the current record's "chapitre" value
 * @method TitreLoi            setSection()          Sets the current record's "section" value
 * @method TitreLoi            setTiTre()            Sets the current record's "titre" value
 * @method TitreLoi            setExposE()           Sets the current record's "expose" value
 * @method TitreLoi            setParlementaire_id() Sets the current record's "parlementaire_id" value
 * @method TitreLoi            setDate()             Sets the current record's "date" value
 * @method TitreLoi            setSource()           Sets the current record's "source" value
 * @method TitreLoi            setNb_articles()      Sets the current record's "nb_articles" value
 * @method TitreLoi            setTiTre_loi_id()     Sets the current record's "titre_loi_id" value
 * @method TitreLoi            setParlementaire()    Sets the current record's "Parlementaire" value
 * @method TitreLoi            setTitreLoi()         Sets the current record's "TitreLoi" value
 * @method TitreLoi            setTexteloi()         Sets the current record's "Texteloi" value
 * @method TitreLoi            setArticles()         Sets the current record's "Articles" collection
 * @method TitreLoi            setSousSections()     Sets the current record's "SousSections" collection
 * 
 * @package    senat
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTitreLoi extends ObjectCommentable
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('titre_loi');
        $this->hasColumn('texteloi_id', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('chapitre', 'string', 8, array(
             'type' => 'string',
             'length' => 8,
             ));
        $this->hasColumn('section', 'string', 8, array(
             'type' => 'string',
             'length' => 8,
             ));
        $this->hasColumn('titre', 'string', 512, array(
             'type' => 'string',
             'length' => 512,
             ));
        $this->hasColumn('expose', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('parlementaire_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('source', 'string', 128, array(
             'type' => 'string',
             'unique' => true,
             'length' => 128,
             ));
        $this->hasColumn('nb_articles', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('titre_loi_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Parlementaire', array(
             'local' => 'parlementaire_id',
             'foreign' => 'id'));

        $this->hasOne('TitreLoi', array(
             'local' => 'titre_loi_id',
             'foreign' => 'id'));

        $this->hasOne('Texteloi', array(
             'local' => 'texteloi_id',
             'foreign' => 'id'));

        $this->hasMany('ArticleLoi as Articles', array(
             'local' => 'id',
             'foreign' => 'titre_loi_id'));

        $this->hasMany('TitreLoi as SousSections', array(
             'local' => 'id',
             'foreign' => 'titre_loi_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}