<?php

/**
 * BaseParlementaireTexteloi
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $parlementaire_id
 * @property string $texteloi_id
 * @property integer $importance
 * @property string $fonction
 * @property Parlementaire $Parlementaire
 * @property Texteloi $Texteloi
 * 
 * @method integer               getParlementaire_id() Returns the current record's "parlementaire_id" value
 * @method string                getTexTeloi_id()      Returns the current record's "texteloi_id" value
 * @method integer               getImportance()       Returns the current record's "importance" value
 * @method string                getFonction()         Returns the current record's "fonction" value
 * @method Parlementaire         getParlementaire()    Returns the current record's "Parlementaire" value
 * @method Texteloi              getTexteloi()         Returns the current record's "Texteloi" value
 * @method ParlementaireTexteloi setParlementaire_id() Sets the current record's "parlementaire_id" value
 * @method ParlementaireTexteloi setTexTeloi_id()      Sets the current record's "texteloi_id" value
 * @method ParlementaireTexteloi setImportance()       Sets the current record's "importance" value
 * @method ParlementaireTexteloi setFonction()         Sets the current record's "fonction" value
 * @method ParlementaireTexteloi setParlementaire()    Sets the current record's "Parlementaire" value
 * @method ParlementaireTexteloi setTexteloi()         Sets the current record's "Texteloi" value
 * 
 * @package    senat
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseParlementaireTexteloi extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('parlementaire_texteloi');
        $this->hasColumn('parlementaire_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('texteloi_id', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('importance', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('fonction', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Parlementaire', array(
             'local' => 'parlementaire_id',
             'foreign' => 'id'));

        $this->hasOne('Texteloi', array(
             'local' => 'texteloi_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}