<?php

/**
 * BaseSeance
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $date
 * @property integer $numero_semaine
 * @property integer $annee
 * @property enum $type
 * @property string $moment
 * @property integer $organisme_id
 * @property boolean $tagged
 * @property string $session
 * @property Organisme $Organisme
 * @property Doctrine_Collection $Presences
 * @property Doctrine_Collection $Interventions
 * 
 * @method date                getDate()           Returns the current record's "date" value
 * @method integer             getNumero_semaiNe() Returns the current record's "numero_semaine" value
 * @method integer             getAnnee()          Returns the current record's "annee" value
 * @method enum                getType()           Returns the current record's "type" value
 * @method string              getMoMent()         Returns the current record's "moment" value
 * @method integer             getOrganisme_id()   Returns the current record's "organisme_id" value
 * @method boolean             getTagged()         Returns the current record's "tagged" value
 * @method string              getSeSSion()        Returns the current record's "session" value
 * @method Organisme           getOrganisme()      Returns the current record's "Organisme" value
 * @method Doctrine_Collection getPresences()      Returns the current record's "Presences" collection
 * @method Doctrine_Collection getInterventions()  Returns the current record's "Interventions" collection
 * @method Seance              setDate()           Sets the current record's "date" value
 * @method Seance              setNumero_semaiNe() Sets the current record's "numero_semaine" value
 * @method Seance              setAnnee()          Sets the current record's "annee" value
 * @method Seance              setType()           Sets the current record's "type" value
 * @method Seance              setMoMent()         Sets the current record's "moment" value
 * @method Seance              setOrganisme_id()   Sets the current record's "organisme_id" value
 * @method Seance              setTagged()         Sets the current record's "tagged" value
 * @method Seance              setSeSSion()        Sets the current record's "session" value
 * @method Seance              setOrganisme()      Sets the current record's "Organisme" value
 * @method Seance              setPresences()      Sets the current record's "Presences" collection
 * @method Seance              setInterventions()  Sets the current record's "Interventions" collection
 * 
 * @package    senat
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSeance extends ObjectCommentable
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('seance');
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('numero_semaine', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('annee', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'commission',
              1 => 'hemicycle',
             ),
             ));
        $this->hasColumn('moment', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('organisme_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('tagged', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('session', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));


        $this->index('uniq_index', array(
             'fields' => 
             array(
              0 => 'organisme_id',
              1 => 'date',
              2 => 'moment',
             ),
             'type' => 'unique',
             ));
        $this->index('index_session', array(
             'fields' => 
             array(
              0 => 'session',
             ),
             ));
        $this->index('index_semaine', array(
             'fields' => 
             array(
              0 => 'annee',
              1 => 'numero_semaine',
             ),
             ));
        $this->index('index_annee', array(
             'fields' => 
             array(
              0 => 'annee',
             ),
             ));
        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Organisme', array(
             'local' => 'organisme_id',
             'foreign' => 'id'));

        $this->hasMany('Presence as Presences', array(
             'local' => 'id',
             'foreign' => 'seance_id'));

        $this->hasMany('Intervention as Interventions', array(
             'local' => 'id',
             'foreign' => 'seance_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}