<?php

/**
 * BaseParlementairePhoto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string              $slug                 Type: string(255)
 * @property string              $photo                Type: clob
 *  
 * @method string                getSlug()             Type: string(255)
 * @method string                getPhoto()            Type: clob
 *  
 * @method ParlementairePhoto    setSlug(string $val)  Type: string(255)
 * @method ParlementairePhoto    setPhoto(string $val) Type: clob
 *  
 * @package    cpc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseParlementairePhoto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('parlementaire_photo');
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('photo', 'clob', null, array(
             'type' => 'clob',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}