<?php

/**
 * BaseAlinea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string      $texteloi_id                Type: string(16)
 * @property int         $article_loi_id             Type: integer
 * @property int         $numero                     Type: integer
 * @property string      $texte                      Type: string
 * @property string      $ref_loi                    Type: string(255)
 * @property ArticleLoi  $Article                    
 * @property Texteloi    $Texteloi                   
 *  
 * @method string        getTexteloiId()             Type: string(16)
 * @method int           getArticleLoiId()           Type: integer
 * @method int           getNumero()                 Type: integer
 * @method string        getTexte()                  Type: string
 * @method string        getRefLoi()                 Type: string(255)
 * @method ArticleLoi    getArticle()                
 * @method Texteloi      getTexteloi()               
 *  
 * @method Alinea        setTexteloiId(string $val)  Type: string(16)
 * @method Alinea        setArticleLoiId(int $val)   Type: integer
 * @method Alinea        setNumero(int $val)         Type: integer
 * @method Alinea        setTexte(string $val)       Type: string
 * @method Alinea        setRefLoi(string $val)      Type: string(255)
 * @method Alinea        setArticle(ArticleLoi $val) 
 * @method Alinea        setTexteloi(Texteloi $val)  
 *  
 * @package    cpc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAlinea extends ObjectCommentable
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('alinea');
        $this->hasColumn('texteloi_id', 'string', 16, array(
             'type' => 'string',
             'length' => 16,
             ));
        $this->hasColumn('article_loi_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('numero', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('texte', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ref_loi', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));


        $this->index('iarticleloinumero', array(
             'fields' => 
             array(
              0 => 'texteloi_id',
              1 => 'article_loi_id',
              2 => 'numero',
             ),
             'type' => 'unique',
             ));
        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ArticleLoi as Article', array(
             'local' => 'article_loi_id',
             'foreign' => 'id'));

        $this->hasOne('Texteloi', array(
             'local' => 'texteloi_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}