<?php

/**
 * BaseParlementaireTexteloi
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                    $parlementaire_id                           Type: integer
 * @property string                 $parlementaire_groupe_acronyme              Type: string(16)
 * @property string                 $texteloi_id                                Type: string(16)
 * @property int                    $importance                                 Type: integer
 * @property string                 $fonction                                   Type: string(255)
 * @property Parlementaire          $Parlementaire                              
 * @property Texteloi               $Texteloi                                   
 *  
 * @method int                      getParlementaireId()                        Type: integer
 * @method string                   getParlementaireGroupeAcronyme()            Type: string(16)
 * @method string                   getTexteloiId()                             Type: string(16)
 * @method int                      getImportance()                             Type: integer
 * @method string                   getFonction()                               Type: string(255)
 * @method Parlementaire            getParlementaire()                          
 * @method Texteloi                 getTexteloi()                               
 *  
 * @method ParlementaireTexteloi    setParlementaireId(int $val)                Type: integer
 * @method ParlementaireTexteloi    setParlementaireGroupeAcronyme(string $val) Type: string(16)
 * @method ParlementaireTexteloi    setTexteloiId(string $val)                  Type: string(16)
 * @method ParlementaireTexteloi    setImportance(int $val)                     Type: integer
 * @method ParlementaireTexteloi    setFonction(string $val)                    Type: string(255)
 * @method ParlementaireTexteloi    setParlementaire(Parlementaire $val)        
 * @method ParlementaireTexteloi    setTexteloi(Texteloi $val)                  
 *  
 * @package    cpc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseParlementaireTexteloi extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('parlementaire_texteloi');
        $this->hasColumn('parlementaire_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('parlementaire_groupe_acronyme', 'string', 16, array(
             'type' => 'string',
             'length' => 16,
             ));
        $this->hasColumn('texteloi_id', 'string', 16, array(
             'type' => 'string',
             'length' => 16,
             ));
        $this->hasColumn('importance', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('fonction', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Parlementaire', array(
             'local' => 'parlementaire_id',
             'foreign' => 'id'));

        $this->hasOne('Texteloi', array(
             'local' => 'texteloi_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}