<?php

/**
 * BaseAmendement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $source
 * @property string $texteloi_id
 * @property string $numero
 * @property integer $rectif
 * @property string $sujet
 * @property enum $sort
 * @property enum $avis_comm
 * @property enum $avis_gouv
 * @property date $date
 * @property string $signataires
 * @property string $texte
 * @property string $expose
 * @property string $ref_loi
 * @property integer $organisme_id
 * @property integer $numero_pere
 * @property string $content_md5
 * @property Doctrine_Collection $Parlementaires
 * @property Texteloi $Texteloi
 * @property Organisme $Commission
 * @property Doctrine_Collection $ParlementaireAmendements
 * 
 * @method string              getSource()                   Returns the current record's "source" value
 * @method string              getTexTeloi_id()              Returns the current record's "texteloi_id" value
 * @method string              getNumero()                   Returns the current record's "numero" value
 * @method integer             getRectif()                   Returns the current record's "rectif" value
 * @method string              getSujet()                    Returns the current record's "sujet" value
 * @method enum                getSort()                     Returns the current record's "sort" value
 * @method enum                getAvis_comm()                Returns the current record's "avis_comm" value
 * @method enum                getAvis_gouv()                Returns the current record's "avis_gouv" value
 * @method date                getDate()                     Returns the current record's "date" value
 * @method string              getSignataireS()              Returns the current record's "signataires" value
 * @method string              getTexTe()                    Returns the current record's "texte" value
 * @method string              getExposE()                   Returns the current record's "expose" value
 * @method string              getRef_loi()                  Returns the current record's "ref_loi" value
 * @method integer             getOrganisme_id()             Returns the current record's "organisme_id" value
 * @method integer             getNumero_pere()              Returns the current record's "numero_pere" value
 * @method string              getContent_md5()              Returns the current record's "content_md5" value
 * @method Doctrine_Collection getParlementaires()           Returns the current record's "Parlementaires" collection
 * @method Texteloi            getTexteloi()                 Returns the current record's "Texteloi" value
 * @method Organisme           getCommission()               Returns the current record's "Commission" value
 * @method Doctrine_Collection getParlementaireAmendements() Returns the current record's "ParlementaireAmendements" collection
 * @method Amendement          setSource()                   Sets the current record's "source" value
 * @method Amendement          setTexTeloi_id()              Sets the current record's "texteloi_id" value
 * @method Amendement          setNumero()                   Sets the current record's "numero" value
 * @method Amendement          setRectif()                   Sets the current record's "rectif" value
 * @method Amendement          setSujet()                    Sets the current record's "sujet" value
 * @method Amendement          setSort()                     Sets the current record's "sort" value
 * @method Amendement          setAvis_comm()                Sets the current record's "avis_comm" value
 * @method Amendement          setAvis_gouv()                Sets the current record's "avis_gouv" value
 * @method Amendement          setDate()                     Sets the current record's "date" value
 * @method Amendement          setSignataireS()              Sets the current record's "signataires" value
 * @method Amendement          setTexTe()                    Sets the current record's "texte" value
 * @method Amendement          setExposE()                   Sets the current record's "expose" value
 * @method Amendement          setRef_loi()                  Sets the current record's "ref_loi" value
 * @method Amendement          setOrganisme_id()             Sets the current record's "organisme_id" value
 * @method Amendement          setNumero_pere()              Sets the current record's "numero_pere" value
 * @method Amendement          setContent_md5()              Sets the current record's "content_md5" value
 * @method Amendement          setParlementaires()           Sets the current record's "Parlementaires" collection
 * @method Amendement          setTexteloi()                 Sets the current record's "Texteloi" value
 * @method Amendement          setCommission()               Sets the current record's "Commission" value
 * @method Amendement          setParlementaireAmendements() Sets the current record's "ParlementaireAmendements" collection
 * 
 * @package    senat
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAmendement extends ObjectCommentable
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('amendement');
        $this->hasColumn('source', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('texteloi_id', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('numero', 'string', 8, array(
             'type' => 'string',
             'length' => 8,
             ));
        $this->hasColumn('rectif', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('sujet', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('sort', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Indéfini',
              1 => 'Adopté',
              2 => 'Irrecevable',
              3 => 'Rejeté',
              4 => 'Retiré',
              5 => 'Tombe',
              6 => 'Non soutenu',
              7 => 'Retiré avant séance',
              8 => 'Rectifié',
              9 => 'Satisfait',
             ),
             ));
        $this->hasColumn('avis_comm', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Indéfini',
              1 => 'Favorable',
              2 => 'Défavorable',
              3 => 'Demande de retrait',
              4 => 'Sagesse',
             ),
             ));
        $this->hasColumn('avis_gouv', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Indéfini',
              1 => 'Favorable',
              2 => 'Défavorable',
              3 => 'Demande de retrait',
              4 => 'Sagesse',
             ),
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('signataires', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('texte', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('expose', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ref_loi', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('organisme_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('numero_pere', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('content_md5', 'string', 36, array(
             'type' => 'string',
             'length' => 36,
             ));


        $this->index('ft_amendements', array(
             'fields' => 
             array(
              0 => 'sujet',
              1 => 'texte',
              2 => 'expose',
             ),
             'type' => 'fulltext',
             ));
        $this->index('uniq_loi_num', array(
             'fields' => 
             array(
              0 => 'texteloi_id',
              1 => 'numero',
              2 => 'rectif',
             ),
             'type' => 'unique',
             ));
        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Parlementaire as Parlementaires', array(
             'refClass' => 'ParlementaireAmendement',
             'local' => 'amendement_id',
             'foreign' => 'parlementaire_id'));

        $this->hasOne('Texteloi', array(
             'local' => 'texteloi_id',
             'foreign' => 'id'));

        $this->hasOne('Organisme as Commission', array(
             'local' => 'organisme_id',
             'foreign' => 'id'));

        $this->hasMany('ParlementaireAmendement as ParlementaireAmendements', array(
             'local' => 'id',
             'foreign' => 'amendement_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $taggable0 = new Taggable();
        $solrable0 = new Solrable(array(
             'title' => 
             array(
              0 => 'titre',
             ),
             'description' => 
             array(
              0 => 'expose',
              1 => 'texte',
              2 => 'signataires',
              3 => 'source',
             ),
             'moretags' => 
             array(
              0 => 'Parlementaires',
              1 => 'sort',
             ),
             'date' => 'date',
             'index_if' => 'is_last_version',
             ));
        $this->actAs($timestampable0);
        $this->actAs($taggable0);
        $this->actAs($solrable0);
    }
}