<?php

/**
 * BaseVariableGlobale
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string           $champ                Type: string(32)
 * @property object           $value                Type: blob
 *  
 * @method string             getChamp()            Type: string(32)
 * @method object             getValue()            Type: blob
 *  
 * @method VariableGlobale    setChamp(string $val) Type: string(32)
 * @method VariableGlobale    setValue(object $val) Type: blob
 *  
 * @package    cpc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVariableGlobale extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('variable_globale');
        $this->hasColumn('champ', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('value', 'blob', null, array(
             'type' => 'blob',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}