<?php

/**
 * BaseParlementaire
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nom_circo
 * @property integer $num_circo
 * @property string $sites_web
 * @property date $debut_mandat
 * @property date $fin_mandat
 * @property integer $place_hemicycle
 * @property string $url_institution
 * @property string $profession
 * @property boolean $autoflip
 * @property string $id_institution
 * @property enum $type
 * @property string $groupe_acronyme
 * @property string $parti
 * @property string $adresses
 * @property integer $suppleant_de_id
 * @property string $anciens_mandats
 * @property string $autres_mandats
 * @property string $mails
 * @property string $top
 * @property string $villes
 * @property Doctrine_Collection $Organismes
 * @property Parlementaire $SuppleantDe
 * @property Doctrine_Collection $Suppleants
 * @property Doctrine_Collection $ParlementaireOrganismes
 * @property Doctrine_Collection $Presences
 * @property Doctrine_Collection $Interventions
 * @property Doctrine_Collection $Amendements
 * @property Doctrine_Collection $Questions
 * @property Doctrine_Collection $ParlementaireAmendements
 * @property Doctrine_Collection $Propositions
 * @property Doctrine_Collection $Textelois
 * @property Doctrine_Collection $ParlementaireTextelois
 * 
 * @method string              getNom_circo()                Returns the current record's "nom_circo" value
 * @method integer             getNum_circo()                Returns the current record's "num_circo" value
 * @method string              getSiteS_web()                Returns the current record's "sites_web" value
 * @method date                getDebut_manDat()             Returns the current record's "debut_mandat" value
 * @method date                getFin_mandat()               Returns the current record's "fin_mandat" value
 * @method integer             getPlace_hemicycle()          Returns the current record's "place_hemicycle" value
 * @method string              getUrl_institUtion()          Returns the current record's "url_institution" value
 * @method string              getProfession()               Returns the current record's "profession" value
 * @method boolean             getAutoflip()                 Returns the current record's "autoflip" value
 * @method string              getId_InstItutIon()           Returns the current record's "id_institution" value
 * @method enum                getType()                     Returns the current record's "type" value
 * @method string              getGroupe_acronyme()          Returns the current record's "groupe_acronyme" value
 * @method string              getParti()                    Returns the current record's "parti" value
 * @method string              getAdresses()                 Returns the current record's "adresses" value
 * @method integer             getSuppleant_de_id()          Returns the current record's "suppleant_de_id" value
 * @method string              getAnciens_mAndAts()          Returns the current record's "anciens_mandats" value
 * @method string              getAutres_mAndAts()           Returns the current record's "autres_mandats" value
 * @method string              getMails()                    Returns the current record's "mails" value
 * @method string              getTop()                      Returns the current record's "top" value
 * @method string              getVilles()                   Returns the current record's "villes" value
 * @method Doctrine_Collection getOrganismes()               Returns the current record's "Organismes" collection
 * @method Parlementaire       getSuppleantDe()              Returns the current record's "SuppleantDe" value
 * @method Doctrine_Collection getSuppleants()               Returns the current record's "Suppleants" collection
 * @method Doctrine_Collection getParlementaireOrganismes()  Returns the current record's "ParlementaireOrganismes" collection
 * @method Doctrine_Collection getPresences()                Returns the current record's "Presences" collection
 * @method Doctrine_Collection getInterventions()            Returns the current record's "Interventions" collection
 * @method Doctrine_Collection getAmendements()              Returns the current record's "Amendements" collection
 * @method Doctrine_Collection getQuestions()                Returns the current record's "Questions" collection
 * @method Doctrine_Collection getParlementaireAmendements() Returns the current record's "ParlementaireAmendements" collection
 * @method Doctrine_Collection getPropositions()             Returns the current record's "Propositions" collection
 * @method Doctrine_Collection getTextelois()                Returns the current record's "Textelois" collection
 * @method Doctrine_Collection getParlementaireTextelois()   Returns the current record's "ParlementaireTextelois" collection
 * @method Parlementaire       setNom_circo()                Sets the current record's "nom_circo" value
 * @method Parlementaire       setNum_circo()                Sets the current record's "num_circo" value
 * @method Parlementaire       setSiteS_web()                Sets the current record's "sites_web" value
 * @method Parlementaire       setDebut_manDat()             Sets the current record's "debut_mandat" value
 * @method Parlementaire       setFin_mandat()               Sets the current record's "fin_mandat" value
 * @method Parlementaire       setPlace_hemicycle()          Sets the current record's "place_hemicycle" value
 * @method Parlementaire       setUrl_institUtion()          Sets the current record's "url_institution" value
 * @method Parlementaire       setProfession()               Sets the current record's "profession" value
 * @method Parlementaire       setAutoflip()                 Sets the current record's "autoflip" value
 * @method Parlementaire       setId_InstItutIon()           Sets the current record's "id_institution" value
 * @method Parlementaire       setType()                     Sets the current record's "type" value
 * @method Parlementaire       setGroupe_acronyme()          Sets the current record's "groupe_acronyme" value
 * @method Parlementaire       setParti()                    Sets the current record's "parti" value
 * @method Parlementaire       setAdresses()                 Sets the current record's "adresses" value
 * @method Parlementaire       setSuppleant_de_id()          Sets the current record's "suppleant_de_id" value
 * @method Parlementaire       setAnciens_mAndAts()          Sets the current record's "anciens_mandats" value
 * @method Parlementaire       setAutres_mAndAts()           Sets the current record's "autres_mandats" value
 * @method Parlementaire       setMails()                    Sets the current record's "mails" value
 * @method Parlementaire       setTop()                      Sets the current record's "top" value
 * @method Parlementaire       setVilles()                   Sets the current record's "villes" value
 * @method Parlementaire       setOrganismes()               Sets the current record's "Organismes" collection
 * @method Parlementaire       setSuppleantDe()              Sets the current record's "SuppleantDe" value
 * @method Parlementaire       setSuppleants()               Sets the current record's "Suppleants" collection
 * @method Parlementaire       setParlementaireOrganismes()  Sets the current record's "ParlementaireOrganismes" collection
 * @method Parlementaire       setPresences()                Sets the current record's "Presences" collection
 * @method Parlementaire       setInterventions()            Sets the current record's "Interventions" collection
 * @method Parlementaire       setAmendements()              Sets the current record's "Amendements" collection
 * @method Parlementaire       setQuestions()                Sets the current record's "Questions" collection
 * @method Parlementaire       setParlementaireAmendements() Sets the current record's "ParlementaireAmendements" collection
 * @method Parlementaire       setPropositions()             Sets the current record's "Propositions" collection
 * @method Parlementaire       setTextelois()                Sets the current record's "Textelois" collection
 * @method Parlementaire       setParlementaireTextelois()   Sets the current record's "ParlementaireTextelois" collection
 * 
 * @package    senat
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseParlementaire extends Personnalite
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('parlementaire');
        $this->hasColumn('nom_circo', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('num_circo', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('sites_web', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('debut_mandat', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('fin_mandat', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('place_hemicycle', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('url_institution', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('profession', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('autoflip', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('id_institution', 'string', 64, array(
             'type' => 'string',
             'unique' => true,
             'length' => 64,
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'depute',
              1 => 'senateur',
             ),
             ));
        $this->hasColumn('groupe_acronyme', 'string', 8, array(
             'type' => 'string',
             'length' => 8,
             ));
        $this->hasColumn('parti', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('adresses', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('suppleant_de_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('anciens_mandats', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('autres_mandats', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('mails', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('top', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('villes', 'string', null, array(
             'type' => 'string',
             ));


        $this->index('uniq_url', array(
             'fields' => 
             array(
              0 => 'url_institution',
             ),
             'type' => 'unique',
             ));
        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Organisme as Organismes', array(
             'refClass' => 'ParlementaireOrganisme',
             'local' => 'parlementaire_id',
             'foreign' => 'organisme_id'));

        $this->hasOne('Parlementaire as SuppleantDe', array(
             'local' => 'suppleant_de_id',
             'foreign' => 'id'));

        $this->hasMany('Parlementaire as Suppleants', array(
             'local' => 'id',
             'foreign' => 'suppleant_de_id'));

        $this->hasMany('ParlementaireOrganisme as ParlementaireOrganismes', array(
             'local' => 'id',
             'foreign' => 'parlementaire_id'));

        $this->hasMany('Presence as Presences', array(
             'local' => 'id',
             'foreign' => 'parlementaire_id'));

        $this->hasMany('Intervention as Interventions', array(
             'local' => 'id',
             'foreign' => 'parlementaire_id'));

        $this->hasMany('Amendement as Amendements', array(
             'refClass' => 'ParlementaireAmendement',
             'local' => 'parlementaire_id',
             'foreign' => 'amendement_id'));

        $this->hasMany('Question as Questions', array(
             'local' => 'id',
             'foreign' => 'parlementaire_id'));

        $this->hasMany('ParlementaireAmendement as ParlementaireAmendements', array(
             'local' => 'id',
             'foreign' => 'parlementaire_id'));

        $this->hasMany('TitreLoi as Propositions', array(
             'local' => 'id',
             'foreign' => 'parlementaire_id'));

        $this->hasMany('Texteloi as Textelois', array(
             'refClass' => 'ParlementaireTexteloi',
             'local' => 'parlementaire_id',
             'foreign' => 'texteloi_id'));

        $this->hasMany('ParlementaireTexteloi as ParlementaireTextelois', array(
             'local' => 'id',
             'foreign' => 'parlementaire_id'));

        $solrable0 = new Solrable(array(
             'title' => 
             array(
              0 => 'nom',
              1 => 'statut',
             ),
             'extra_weight' => 3,
             'description' => 
             array(
              0 => 'villes',
             ),
             'moretags' => 
             array(
              0 => 'profession',
             ),
             'date' => 'debut_mandat',
             'no_index_on_save' => true,
             ));
        $this->actAs($solrable0);
    }
}