<?php

/**
 * BaseCommentaireObject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $object_type
 * @property integer $object_id
 * @property integer $commentaire_id
 * @property Commentaire $Commentaire
 * 
 * @method string            getObject_type()    Returns the current record's "object_type" value
 * @method integer           getObject_id()      Returns the current record's "object_id" value
 * @method integer           getCommentaire_id() Returns the current record's "commentaire_id" value
 * @method Commentaire       getCommentaire()    Returns the current record's "Commentaire" value
 * @method CommentaireObject setObject_type()    Sets the current record's "object_type" value
 * @method CommentaireObject setObject_id()      Sets the current record's "object_id" value
 * @method CommentaireObject setCommentaire_id() Sets the current record's "commentaire_id" value
 * @method CommentaireObject setCommentaire()    Sets the current record's "Commentaire" value
 * 
 * @package    senat
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCommentaireObject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('commentaire_object');
        $this->hasColumn('object_type', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('object_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('commentaire_id', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->index('unique', array(
             'fields' => 
             array(
              0 => 'object_type',
              1 => 'object_id',
              2 => 'commentaire_id',
             ),
             'type' => 'unique',
             ));
        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Commentaire', array(
             'local' => 'commentaire_id',
             'foreign' => 'id'));
    }
}