<?php

/**
 * BaseOrganisme
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nom
 * @property enum $type
 * @property Doctrine_Collection $Parlementaires
 * @property Doctrine_Collection $ParlementaireOrganismes
 * @property Doctrine_Collection $Seances
 * @property Doctrine_Collection $Amendements
 * @property Doctrine_Collection $Textelois
 * 
 * @method string              getNom()                     Returns the current record's "nom" value
 * @method enum                getType()                    Returns the current record's "type" value
 * @method Doctrine_Collection getParlementaires()          Returns the current record's "Parlementaires" collection
 * @method Doctrine_Collection getParlementaireOrganismes() Returns the current record's "ParlementaireOrganismes" collection
 * @method Doctrine_Collection getSeances()                 Returns the current record's "Seances" collection
 * @method Doctrine_Collection getAmendements()             Returns the current record's "Amendements" collection
 * @method Doctrine_Collection getTextelois()               Returns the current record's "Textelois" collection
 * @method Organisme           setNom()                     Sets the current record's "nom" value
 * @method Organisme           setType()                    Sets the current record's "type" value
 * @method Organisme           setParlementaires()          Sets the current record's "Parlementaires" collection
 * @method Organisme           setParlementaireOrganismes() Sets the current record's "ParlementaireOrganismes" collection
 * @method Organisme           setSeances()                 Sets the current record's "Seances" collection
 * @method Organisme           setAmendements()             Sets the current record's "Amendements" collection
 * @method Organisme           setTextelois()               Sets the current record's "Textelois" collection
 * 
 * @package    senat
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrganisme extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('organisme');
        $this->hasColumn('nom', 'string', 512, array(
             'type' => 'string',
             'length' => 512,
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'parlementaire',
              1 => 'groupe',
              2 => 'extra',
              3 => 'groupes',
             ),
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Parlementaire as Parlementaires', array(
             'refClass' => 'ParlementaireOrganisme',
             'local' => 'organisme_id',
             'foreign' => 'parlementaire_id'));

        $this->hasMany('ParlementaireOrganisme as ParlementaireOrganismes', array(
             'local' => 'id',
             'foreign' => 'organisme_id'));

        $this->hasMany('Seance as Seances', array(
             'local' => 'id',
             'foreign' => 'organisme_id'));

        $this->hasMany('Amendement as Amendements', array(
             'local' => 'id',
             'foreign' => 'organisme_id'));

        $this->hasMany('Texteloi as Textelois', array(
             'local' => 'id',
             'foreign' => 'organisme_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'nom',
             ),
             'unique' => true,
             ));
        $solrable0 = new Solrable(array(
             'title' => 
             array(
              0 => 'titre',
             ),
             'extra_weight' => 3,
             'moretags' => 
             array(
              0 => 'type',
             ),
             'index_if' => 'has_parlementaires',
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
        $this->actAs($solrable0);
    }
}