<?php

/**
 * BaseTexteloi
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id
 * @property integer $numero
 * @property string $annexe
 * @property enum $type
 * @property string $type_details
 * @property string $categorie
 * @property string $id_dossier_institution
 * @property string $titre
 * @property date $date
 * @property string $source
 * @property integer $organisme_id
 * @property string $signataires
 * @property string $contenu
 * @property Doctrine_Collection $Parlementaires
 * @property Organisme $Organisme
 * @property Doctrine_Collection $Amendements
 * @property Doctrine_Collection $ArticleLois
 * @property Doctrine_Collection $Alineas
 * @property Doctrine_Collection $TitreLois
 * @property Doctrine_Collection $ParlementaireTextelois
 * 
 * @method string              getId()                     Returns the current record's "id" value
 * @method integer             getNumero()                 Returns the current record's "numero" value
 * @method string              getAnnexe()                 Returns the current record's "annexe" value
 * @method enum                getType()                   Returns the current record's "type" value
 * @method string              getType_deTails()           Returns the current record's "type_details" value
 * @method string              getCategorie()              Returns the current record's "categorie" value
 * @method string              getId_dossIer_InstItutIon() Returns the current record's "id_dossier_institution" value
 * @method string              getTiTre()                  Returns the current record's "titre" value
 * @method date                getDate()                   Returns the current record's "date" value
 * @method string              getSource()                 Returns the current record's "source" value
 * @method integer             getOrganisme_id()           Returns the current record's "organisme_id" value
 * @method string              getSignataireS()            Returns the current record's "signataires" value
 * @method string              getContenu()                Returns the current record's "contenu" value
 * @method Doctrine_Collection getParlementaires()         Returns the current record's "Parlementaires" collection
 * @method Organisme           getOrganisme()              Returns the current record's "Organisme" value
 * @method Doctrine_Collection getAmendements()            Returns the current record's "Amendements" collection
 * @method Doctrine_Collection getArticleLois()            Returns the current record's "ArticleLois" collection
 * @method Doctrine_Collection getAlineas()                Returns the current record's "Alineas" collection
 * @method Doctrine_Collection getTitreLois()              Returns the current record's "TitreLois" collection
 * @method Doctrine_Collection getParlementaireTextelois() Returns the current record's "ParlementaireTextelois" collection
 * @method Texteloi            setId()                     Sets the current record's "id" value
 * @method Texteloi            setNumero()                 Sets the current record's "numero" value
 * @method Texteloi            setAnnexe()                 Sets the current record's "annexe" value
 * @method Texteloi            setType()                   Sets the current record's "type" value
 * @method Texteloi            setType_deTails()           Sets the current record's "type_details" value
 * @method Texteloi            setCategorie()              Sets the current record's "categorie" value
 * @method Texteloi            setId_dossIer_InstItutIon() Sets the current record's "id_dossier_institution" value
 * @method Texteloi            setTiTre()                  Sets the current record's "titre" value
 * @method Texteloi            setDate()                   Sets the current record's "date" value
 * @method Texteloi            setSource()                 Sets the current record's "source" value
 * @method Texteloi            setOrganisme_id()           Sets the current record's "organisme_id" value
 * @method Texteloi            setSignataireS()            Sets the current record's "signataires" value
 * @method Texteloi            setContenu()                Sets the current record's "contenu" value
 * @method Texteloi            setParlementaires()         Sets the current record's "Parlementaires" collection
 * @method Texteloi            setOrganisme()              Sets the current record's "Organisme" value
 * @method Texteloi            setAmendements()            Sets the current record's "Amendements" collection
 * @method Texteloi            setArticleLois()            Sets the current record's "ArticleLois" collection
 * @method Texteloi            setAlineas()                Sets the current record's "Alineas" collection
 * @method Texteloi            setTitreLois()              Sets the current record's "TitreLois" collection
 * @method Texteloi            setParlementaireTextelois() Sets the current record's "ParlementaireTextelois" collection
 * 
 * @package    senat
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTexteloi extends ObjectCommentable
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('texteloi');
        $this->hasColumn('id', 'string', 20, array(
             'type' => 'string',
             'unique' => true,
             'length' => 20,
             ));
        $this->hasColumn('numero', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('annexe', 'string', 12, array(
             'type' => 'string',
             'length' => 12,
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Motion',
              1 => 'Proposition de loi',
              2 => 'Proposition de résolution',
              3 => 'Projet de loi',
              4 => 'Texte adopté',
              5 => 'Texte de la commission',
              6 => 'Texte de la commission mixte paritaire',
              7 => 'Lettre',
              8 => 'Rapport',
              9 => 'Rapport d\'information',
              10 => 'Rapport d\'office parlementaire',
              11 => 'Avis',
              12 => 'Rapport de groupe d\'amitié',
              13 => 'Rapport de commission d\'enquête',
             ),
             ));
        $this->hasColumn('type_details', 'string', 512, array(
             'type' => 'string',
             'length' => 512,
             ));
        $this->hasColumn('categorie', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('id_dossier_institution', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('titre', 'string', 512, array(
             'type' => 'string',
             'length' => 512,
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('source', 'string', 128, array(
             'type' => 'string',
             'unique' => true,
             'length' => 128,
             ));
        $this->hasColumn('organisme_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('signataires', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('contenu', 'string', null, array(
             'type' => 'string',
             ));


        $this->index('index_url', array(
             'fields' => 
             array(
              0 => 'id_dossier_institution',
             ),
             ));
        $this->index('index_alpha', array(
             'fields' => 
             array(
              0 => 'numero',
              1 => 'annexe',
             ),
             ));
        $this->index('index_type', array(
             'fields' => 
             array(
              0 => 'type(30)',
              1 => 'type_details(200)',
             ),
             ));
        $this->index('index_date', array(
             'fields' => 
             array(
              0 => 'date',
             ),
             ));
        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Parlementaire as Parlementaires', array(
             'refClass' => 'ParlementaireTexteloi',
             'local' => 'texteloi_id',
             'foreign' => 'parlementaire_id'));

        $this->hasOne('Organisme', array(
             'local' => 'organisme_id',
             'foreign' => 'id'));

        $this->hasMany('Amendement as Amendements', array(
             'local' => 'id',
             'foreign' => 'texteloi_id'));

        $this->hasMany('ArticleLoi as ArticleLois', array(
             'local' => 'id',
             'foreign' => 'texteloi_id'));

        $this->hasMany('Alinea as Alineas', array(
             'local' => 'id',
             'foreign' => 'texteloi_id'));

        $this->hasMany('TitreLoi as TitreLois', array(
             'local' => 'id',
             'foreign' => 'texteloi_id'));

        $this->hasMany('ParlementaireTexteloi as ParlementaireTextelois', array(
             'local' => 'id',
             'foreign' => 'texteloi_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $taggable0 = new Taggable();
        $solrable0 = new Solrable(array(
             'title' => 
             array(
              0 => 'titre',
             ),
             'description' => 
             array(
              0 => 'contenu',
              1 => 'id',
              2 => 'source',
             ),
             'moretags' => 
             array(
              0 => 'categorie',
              1 => 'type',
              2 => 'Organisme',
              3 => 'Parlementaires',
             ),
             'date' => 'date',
             ));
        $this->actAs($timestampable0);
        $this->actAs($taggable0);
        $this->actAs($solrable0);
    }
}