<?php

/**
 * BaseSection
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string                              $md5                                       Type: string(36), unique
 * @property string                              $titre                                     Type: string(256)
 * @property string                              $titre_complet                             Type: string(512)
 * @property int                                 $section_id                                Type: integer
 * @property string                              $min_date                                  Type: string(15)
 * @property string                              $max_date                                  Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @property int                                 $timestamp                                 Type: integer
 * @property int                                 $nb_interventions                          Type: integer
 * @property string                              $id_dossier_an                             Type: string(255)
 * @property Section                             $Section                                   
 * @property Doctrine_Collection|Section[]       $SubSections                               
 * @property Doctrine_Collection|Intervention[]  $Interventions                             
 *  
 * @method string                                getMd5()                                   Type: string(36), unique
 * @method string                                getTitre()                                 Type: string(256)
 * @method string                                getTitreComplet()                          Type: string(512)
 * @method int                                   getSectionId()                             Type: integer
 * @method string                                getMinDate()                               Type: string(15)
 * @method string                                getMaxDate()                               Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @method int                                   getTimestamp()                             Type: integer
 * @method int                                   getNbInterventions()                       Type: integer
 * @method string                                getIdDossierAn()                           Type: string(255)
 * @method Section                               getSection()                               
 * @method Doctrine_Collection|Section[]         getSubSections()                           
 * @method Doctrine_Collection|Intervention[]    getInterventions()                         
 *  
 * @method Section                               setMd5(string $val)                        Type: string(36), unique
 * @method Section                               setTitre(string $val)                      Type: string(256)
 * @method Section                               setTitreComplet(string $val)               Type: string(512)
 * @method Section                               setSectionId(int $val)                     Type: integer
 * @method Section                               setMinDate(string $val)                    Type: string(15)
 * @method Section                               setMaxDate(string $val)                    Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @method Section                               setTimestamp(int $val)                     Type: integer
 * @method Section                               setNbInterventions(int $val)               Type: integer
 * @method Section                               setIdDossierAn(string $val)                Type: string(255)
 * @method Section                               setSection(Section $val)                   
 * @method Section                               setSubSections(Doctrine_Collection $val)   
 * @method Section                               setInterventions(Doctrine_Collection $val) 
 *  
 * @package    cpc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSection extends ObjectCommentable
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('section');
        $this->hasColumn('md5', 'string', 36, array(
             'type' => 'string',
             'unique' => true,
             'length' => 36,
             ));
        $this->hasColumn('titre', 'string', 256, array(
             'type' => 'string',
             'length' => 256,
             ));
        $this->hasColumn('titre_complet', 'string', 512, array(
             'type' => 'string',
             'length' => 512,
             ));
        $this->hasColumn('section_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('min_date', 'string', 15, array(
             'type' => 'string',
             'length' => 15,
             ));
        $this->hasColumn('max_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('timestamp', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('nb_interventions', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('id_dossier_an', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Section', array(
             'local' => 'section_id',
             'foreign' => 'id'));

        $this->hasMany('Section as SubSections', array(
             'local' => 'id',
             'foreign' => 'section_id'));

        $this->hasMany('Intervention as Interventions', array(
             'local' => 'id',
             'foreign' => 'section_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $taggable0 = new Taggable();
        $solrable0 = new Solrable(array(
             'title' => 
             array(
              0 => 'titre',
             ),
             'moretags' => 
             array(
              0 => 'Parlementaires',
              1 => 'link_source',
             ),
             'extra_weight' => 2,
             'index_if' => 'is_parent',
             'date' => 'max_date',
             ));
        $this->actAs($timestampable0);
        $this->actAs($taggable0);
        $this->actAs($solrable0);
    }
}