<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseParlementaire extends Personnalite
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('parlementaire');
        $this->hasColumn('nom_circo', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('num_circo', 'integer', null, array('type' => 'integer'));
        $this->hasColumn('site_web', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('debut_mandat', 'date', null, array('type' => 'date'));
        $this->hasColumn('place_hemicycle', 'integer', null, array('type' => 'integer'));
        $this->hasColumn('url_an', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('profession', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('id_an', 'integer', null, array('type' => 'integer', 'unique' => true));
        $this->hasColumn('type', 'enum', null, array('type' => 'enum', 'values' => array(0 => 'depute', 1 => 'senateur')));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasMany('Organisme as Organismes', array('refClass' => 'ParlementaireOrganisme',
                                                        'local' => 'parlementaire_id',
                                                        'foreign' => 'organisme_id'));

        $this->hasMany('ParlementaireOrganisme as ParlementaireOrganismes', array('local' => 'id',
                                                                                  'foreign' => 'parlementaire_id'));
    }
}