<?php

/**
 * BasePersonnalite
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string                              $nom                                       Type: string(255)
 * @property string                              $nom_de_famille                            Type: string(255)
 * @property string                              $sexe                                      Type: enum, Possible values (H, F)
 * @property string                              $date_naissance                            Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @property string                              $lieu_naissance                            Type: string(255)
 * @property Doctrine_Collection|Intervention[]  $Interventions                             
 *  
 * @method string                                getNom()                                   Type: string(255)
 * @method string                                getNomDeFamille()                          Type: string(255)
 * @method string                                getSexe()                                  Type: enum, Possible values (H, F)
 * @method string                                getDateNaissance()                         Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @method string                                getLieuNaissance()                         Type: string(255)
 * @method Doctrine_Collection|Intervention[]    getInterventions()                         
 *  
 * @method Personnalite                          setNom(string $val)                        Type: string(255)
 * @method Personnalite                          setNomDeFamille(string $val)               Type: string(255)
 * @method Personnalite                          setSexe(string $val)                       Type: enum, Possible values (H, F)
 * @method Personnalite                          setDateNaissance(string $val)              Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @method Personnalite                          setLieuNaissance(string $val)              Type: string(255)
 * @method Personnalite                          setInterventions(Doctrine_Collection $val) 
 *  
 * @package    cpc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePersonnalite extends ObjectCommentable
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('personnalite');
        $this->hasColumn('nom', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('nom_de_famille', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('sexe', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'H',
              1 => 'F',
             ),
             ));
        $this->hasColumn('date_naissance', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('lieu_naissance', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Intervention as Interventions', array(
             'local' => 'id',
             'foreign' => 'personnalite_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'nom',
             ),
             'unique' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}