<?php

/**
 * BaseScrutin
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                                         $numero                                    Type: integer
 * @property int                                         $annee                                     Type: integer
 * @property int                                         $numero_semaine                            Type: integer
 * @property string                                      $date                                      Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @property int                                         $seance_id                                 Type: integer
 * @property int                                         $nombre_votants                            Type: integer
 * @property int                                         $nombre_pours                              Type: integer
 * @property int                                         $nombre_contres                            Type: integer
 * @property int                                         $nombre_abstentions                        Type: integer
 * @property string                                      $type                                      Type: enum, Possible values (ORDINAIRE, SOLENNEL)
 * @property string                                      $sort                                      Type: enum, Possible values (ADOPTé, REJETé)
 * @property text                                        $titre                                     Type: text
 * @property int                                         $texteloi_id                               Type: integer
 * @property int                                         $amendement_id                             Type: integer
 * @property text                                        $sujet                                     Type: text
 * @property text                                        $demandeurs                                Type: text
 * @property string                                      $demandeurs_groupes_acronymes              Type: string(64)
 * @property string                                      $avis_gouvernement                         Type: string(16)
 * @property string                                      $avis_rapporteur                           Type: string(16)
 * @property Seance                                      $Seance                                    
 * @property Texteloi                                    $Texteloi                                  
 * @property Amendement                                  $Amendement                                
 * @property Doctrine_Collection|ParlementaireScrutin[]  $Votes                                     
 *  
 * @method int                                           getNumero()                                Type: integer
 * @method int                                           getAnnee()                                 Type: integer
 * @method int                                           getNumeroSemaine()                         Type: integer
 * @method string                                        getDate()                                  Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @method int                                           getSeanceId()                              Type: integer
 * @method int                                           getNombreVotants()                         Type: integer
 * @method int                                           getNombrePours()                           Type: integer
 * @method int                                           getNombreContres()                         Type: integer
 * @method int                                           getNombreAbstentions()                     Type: integer
 * @method string                                        getType()                                  Type: enum, Possible values (ORDINAIRE, SOLENNEL)
 * @method string                                        getSort()                                  Type: enum, Possible values (ADOPTé, REJETé)
 * @method text                                          getTitre()                                 Type: text
 * @method int                                           getTexteloiId()                            Type: integer
 * @method int                                           getAmendementId()                          Type: integer
 * @method text                                          getSujet()                                 Type: text
 * @method text                                          getDemandeurs()                            Type: text
 * @method string                                        getDemandeursGroupesAcronymes()            Type: string(64)
 * @method string                                        getAvisGouvernement()                      Type: string(16)
 * @method string                                        getAvisRapporteur()                        Type: string(16)
 * @method Seance                                        getSeance()                                
 * @method Texteloi                                      getTexteloi()                              
 * @method Amendement                                    getAmendement()                            
 * @method Doctrine_Collection|ParlementaireScrutin[]    getVotes()                                 
 *  
 * @method Scrutin                                       setNumero(int $val)                        Type: integer
 * @method Scrutin                                       setAnnee(int $val)                         Type: integer
 * @method Scrutin                                       setNumeroSemaine(int $val)                 Type: integer
 * @method Scrutin                                       setDate(string $val)                       Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @method Scrutin                                       setSeanceId(int $val)                      Type: integer
 * @method Scrutin                                       setNombreVotants(int $val)                 Type: integer
 * @method Scrutin                                       setNombrePours(int $val)                   Type: integer
 * @method Scrutin                                       setNombreContres(int $val)                 Type: integer
 * @method Scrutin                                       setNombreAbstentions(int $val)             Type: integer
 * @method Scrutin                                       setType(string $val)                       Type: enum, Possible values (ORDINAIRE, SOLENNEL)
 * @method Scrutin                                       setSort(string $val)                       Type: enum, Possible values (ADOPTé, REJETé)
 * @method Scrutin                                       setTitre(text $val)                        Type: text
 * @method Scrutin                                       setTexteloiId(int $val)                    Type: integer
 * @method Scrutin                                       setAmendementId(int $val)                  Type: integer
 * @method Scrutin                                       setSujet(text $val)                        Type: text
 * @method Scrutin                                       setDemandeurs(text $val)                   Type: text
 * @method Scrutin                                       setDemandeursGroupesAcronymes(string $val) Type: string(64)
 * @method Scrutin                                       setAvisGouvernement(string $val)           Type: string(16)
 * @method Scrutin                                       setAvisRapporteur(string $val)             Type: string(16)
 * @method Scrutin                                       setSeance(Seance $val)                     
 * @method Scrutin                                       setTexteloi(Texteloi $val)                 
 * @method Scrutin                                       setAmendement(Amendement $val)             
 * @method Scrutin                                       setVotes(Doctrine_Collection $val)         
 *  
 * @package    cpc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseScrutin extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('scrutin');
        $this->hasColumn('numero', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('annee', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('numero_semaine', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('seance_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('nombre_votants', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('nombre_pours', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('nombre_contres', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('nombre_abstentions', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'ordinaire',
              1 => 'solennel',
             ),
             ));
        $this->hasColumn('sort', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'adopté',
              1 => 'rejeté',
             ),
             ));
        $this->hasColumn('titre', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('texteloi_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('amendement_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('sujet', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('demandeurs', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('demandeurs_groupes_acronymes', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('avis_gouvernement', 'string', 16, array(
             'type' => 'string',
             'length' => 16,
             ));
        $this->hasColumn('avis_rapporteur', 'string', 16, array(
             'type' => 'string',
             'length' => 16,
             ));


        $this->index('uniq_index', array(
             'fields' => 
             array(
              0 => 'numero',
             ),
             'type' => 'unique',
             ));
        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Seance', array(
             'local' => 'seance_id',
             'foreign' => 'id'));

        $this->hasOne('Texteloi', array(
             'local' => 'texteloi_id',
             'foreign' => 'id'));

        $this->hasOne('Amendement', array(
             'local' => 'amendement_id',
             'foreign' => 'id'));

        $this->hasMany('ParlementaireScrutin as Votes', array(
             'local' => 'id',
             'foreign' => 'scrutin_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}