<?php

/**
 * BaseParlementaireOrganisme
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                     $organisme_id                               Type: integer
 * @property int                     $parlementaire_id                           Type: integer
 * @property string                  $parlementaire_groupe_acronyme              Type: string(16)
 * @property string                  $fonction                                   Type: string(512)
 * @property int                     $importance                                 Type: integer
 * @property string                  $debut_fonction                             Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @property string                  $fin_fonction                               Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @property Parlementaire           $Parlementaire                              
 * @property Organisme               $Organisme                                  
 *  
 * @method int                       getOrganismeId()                            Type: integer
 * @method int                       getParlementaireId()                        Type: integer
 * @method string                    getParlementaireGroupeAcronyme()            Type: string(16)
 * @method string                    getFonction()                               Type: string(512)
 * @method int                       getImportance()                             Type: integer
 * @method string                    getDebutFonction()                          Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @method string                    getFinFonction()                            Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @method Parlementaire             getParlementaire()                          
 * @method Organisme                 getOrganisme()                              
 *  
 * @method ParlementaireOrganisme    setOrganismeId(int $val)                    Type: integer
 * @method ParlementaireOrganisme    setParlementaireId(int $val)                Type: integer
 * @method ParlementaireOrganisme    setParlementaireGroupeAcronyme(string $val) Type: string(16)
 * @method ParlementaireOrganisme    setFonction(string $val)                    Type: string(512)
 * @method ParlementaireOrganisme    setImportance(int $val)                     Type: integer
 * @method ParlementaireOrganisme    setDebutFonction(string $val)               Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @method ParlementaireOrganisme    setFinFonction(string $val)                 Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @method ParlementaireOrganisme    setParlementaire(Parlementaire $val)        
 * @method ParlementaireOrganisme    setOrganisme(Organisme $val)                
 *  
 * @package    cpc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseParlementaireOrganisme extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('parlementaire_organisme');
        $this->hasColumn('organisme_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('parlementaire_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('parlementaire_groupe_acronyme', 'string', 16, array(
             'type' => 'string',
             'length' => 16,
             ));
        $this->hasColumn('fonction', 'string', 512, array(
             'type' => 'string',
             'length' => 512,
             ));
        $this->hasColumn('importance', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('debut_fonction', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('fin_fonction', 'date', null, array(
             'type' => 'date',
             ));


        $this->index('uniq_index', array(
             'fields' => 
             array(
              0 => 'organisme_id',
              1 => 'parlementaire_id',
              2 => 'fin_fonction',
             ),
             'type' => 'unique',
             ));
        $this->index('index_parl', array(
             'fields' => 
             array(
              0 => 'parlementaire_id',
             ),
             ));
        $this->index('index_cur_parl', array(
             'fields' => 
             array(
              0 => 'parlementaire_id',
              1 => 'fin_fonction',
             ),
             ));
        $this->index('index_org', array(
             'fields' => 
             array(
              0 => 'organisme_id',
             ),
             ));
        $this->index('index_cur_org', array(
             'fields' => 
             array(
              0 => 'organisme_id',
              1 => 'fin_fonction',
             ),
             ));
        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Parlementaire', array(
             'local' => 'parlementaire_id',
             'foreign' => 'id'));

        $this->hasOne('Organisme', array(
             'local' => 'organisme_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}