<?php

/**
 * BasePresence
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $parlementaire_id
 * @property integer $seance_id
 * @property integer $nb_preuves
 * @property date $date
 * @property Parlementaire $Parlementaire
 * @property Seance $Seance
 * @property Doctrine_Collection $Preuves
 * 
 * @method integer             getParlementaire_id() Returns the current record's "parlementaire_id" value
 * @method integer             getSeance_id()        Returns the current record's "seance_id" value
 * @method integer             getNb_preuves()       Returns the current record's "nb_preuves" value
 * @method date                getDate()             Returns the current record's "date" value
 * @method Parlementaire       getParlementaire()    Returns the current record's "Parlementaire" value
 * @method Seance              getSeance()           Returns the current record's "Seance" value
 * @method Doctrine_Collection getPreuves()          Returns the current record's "Preuves" collection
 * @method Presence            setParlementaire_id() Sets the current record's "parlementaire_id" value
 * @method Presence            setSeance_id()        Sets the current record's "seance_id" value
 * @method Presence            setNb_preuves()       Sets the current record's "nb_preuves" value
 * @method Presence            setDate()             Sets the current record's "date" value
 * @method Presence            setParlementaire()    Sets the current record's "Parlementaire" value
 * @method Presence            setSeance()           Sets the current record's "Seance" value
 * @method Presence            setPreuves()          Sets the current record's "Preuves" collection
 * 
 * @package    senat
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePresence extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('presence');
        $this->hasColumn('parlementaire_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('seance_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('nb_preuves', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Parlementaire', array(
             'local' => 'parlementaire_id',
             'foreign' => 'id'));

        $this->hasOne('Seance', array(
             'local' => 'seance_id',
             'foreign' => 'id'));

        $this->hasMany('PreuvePresence as Preuves', array(
             'local' => 'id',
             'foreign' => 'presence_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}