<?php

/**
 * BaseArticleLoi
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $texteloi_id
 * @property string $titre
 * @property integer $ordre
 * @property string $precedent
 * @property string $suivant
 * @property string $expose
 * @property integer $titre_loi_id
 * @property TitreLoi $TitreLoi
 * @property Texteloi $Texteloi
 * @property Doctrine_Collection $Alineas
 * 
 * @method string              getTexTeloi_id()  Returns the current record's "texteloi_id" value
 * @method string              getTiTre()        Returns the current record's "titre" value
 * @method integer             getOrdre()        Returns the current record's "ordre" value
 * @method string              getPrecedent()    Returns the current record's "precedent" value
 * @method string              getSuivant()      Returns the current record's "suivant" value
 * @method string              getExposE()       Returns the current record's "expose" value
 * @method integer             getTiTre_loi_id() Returns the current record's "titre_loi_id" value
 * @method TitreLoi            getTitreLoi()     Returns the current record's "TitreLoi" value
 * @method Texteloi            getTexteloi()     Returns the current record's "Texteloi" value
 * @method Doctrine_Collection getAlineas()      Returns the current record's "Alineas" collection
 * @method ArticleLoi          setTexTeloi_id()  Sets the current record's "texteloi_id" value
 * @method ArticleLoi          setTiTre()        Sets the current record's "titre" value
 * @method ArticleLoi          setOrdre()        Sets the current record's "ordre" value
 * @method ArticleLoi          setPrecedent()    Sets the current record's "precedent" value
 * @method ArticleLoi          setSuivant()      Sets the current record's "suivant" value
 * @method ArticleLoi          setExposE()       Sets the current record's "expose" value
 * @method ArticleLoi          setTiTre_loi_id() Sets the current record's "titre_loi_id" value
 * @method ArticleLoi          setTitreLoi()     Sets the current record's "TitreLoi" value
 * @method ArticleLoi          setTexteloi()     Sets the current record's "Texteloi" value
 * @method ArticleLoi          setAlineas()      Sets the current record's "Alineas" collection
 * 
 * @package    senat
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArticleLoi extends ObjectCommentable
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('article_loi');
        $this->hasColumn('texteloi_id', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('titre', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('ordre', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('precedent', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('suivant', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('expose', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('titre_loi_id', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->index('iloititre', array(
             'fields' => 
             array(
              0 => 'texteloi_id',
              1 => 'titre',
             ),
             'type' => 'unique',
             ));
        $this->index('iloiarticle', array(
             'fields' => 
             array(
              0 => 'texteloi_id',
              1 => 'ordre',
             ),
             ));
        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TitreLoi', array(
             'local' => 'titre_loi_id',
             'foreign' => 'id'));

        $this->hasOne('Texteloi', array(
             'local' => 'texteloi_id',
             'foreign' => 'id'));

        $this->hasMany('Alinea as Alineas', array(
             'local' => 'id',
             'foreign' => 'article_loi_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'titre',
             ),
             'unique' => false,
             ));
        $this->actAs($sluggable0);
    }
}