<?php

/**
 * BaseAlerte
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string   $email                     Type: string(128)
 * @property string   $query                     Type: string
 * @property string   $filter                    Type: string
 * @property string   $query_md5                 Type: string(32)
 * @property string   $titre                     Type: string
 * @property bool     $confirmed                 Type: boolean
 * @property bool     $no_human_query            Type: boolean
 * @property string   $period                    Type: enum, Possible values (HOUR, DAY, WEEK, MONTH)
 * @property string   $next_mail                 Type: datetime, Date and time in ISO-8601 format (YYYY-MM-DD HH:MI)
 * @property string   $last_mail                 Type: datetime, Date and time in ISO-8601 format (YYYY-MM-DD HH:MI)
 * @property int      $citoyen_id                Type: integer
 * @property string   $verif                     Type: string(128)
 * @property Citoyen  $Citoyen                   
 *  
 * @method string     getEmail()                 Type: string(128)
 * @method string     getQuery()                 Type: string
 * @method string     getFilter()                Type: string
 * @method string     getQueryMd5()              Type: string(32)
 * @method string     getTitre()                 Type: string
 * @method bool       getConfirmed()             Type: boolean
 * @method bool       getNoHumanQuery()          Type: boolean
 * @method string     getPeriod()                Type: enum, Possible values (HOUR, DAY, WEEK, MONTH)
 * @method string     getNextMail()              Type: datetime, Date and time in ISO-8601 format (YYYY-MM-DD HH:MI)
 * @method string     getLastMail()              Type: datetime, Date and time in ISO-8601 format (YYYY-MM-DD HH:MI)
 * @method int        getCitoyenId()             Type: integer
 * @method string     getVerif()                 Type: string(128)
 * @method Citoyen    getCitoyen()               
 *  
 * @method Alerte     setEmail(string $val)      Type: string(128)
 * @method Alerte     setQuery(string $val)      Type: string
 * @method Alerte     setFilter(string $val)     Type: string
 * @method Alerte     setQueryMd5(string $val)   Type: string(32)
 * @method Alerte     setTitre(string $val)      Type: string
 * @method Alerte     setConfirmed(bool $val)    Type: boolean
 * @method Alerte     setNoHumanQuery(bool $val) Type: boolean
 * @method Alerte     setPeriod(string $val)     Type: enum, Possible values (HOUR, DAY, WEEK, MONTH)
 * @method Alerte     setNextMail(string $val)   Type: datetime, Date and time in ISO-8601 format (YYYY-MM-DD HH:MI)
 * @method Alerte     setLastMail(string $val)   Type: datetime, Date and time in ISO-8601 format (YYYY-MM-DD HH:MI)
 * @method Alerte     setCitoyenId(int $val)     Type: integer
 * @method Alerte     setVerif(string $val)      Type: string(128)
 * @method Alerte     setCitoyen(Citoyen $val)   
 *  
 * @package    cpc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAlerte extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('alerte');
        $this->hasColumn('email', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('query', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('filter', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('query_md5', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('titre', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('confirmed', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('no_human_query', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('period', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'HOUR',
              1 => 'DAY',
              2 => 'WEEK',
              3 => 'MONTH',
             ),
             ));
        $this->hasColumn('next_mail', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('last_mail', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('citoyen_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('verif', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));


        $this->index('index_uniq', array(
             'fields' => 
             array(
              0 => 'email',
              1 => 'citoyen_id',
              2 => 'query_md5',
             ),
             'type' => 'unique',
             ));
        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Citoyen', array(
             'local' => 'citoyen_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}