<?php

/**
 * BaseAlerte
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $email
 * @property string $query
 * @property string $filter
 * @property string $query_md5
 * @property string $titre
 * @property boolean $confirmed
 * @property boolean $no_human_query
 * @property enum $period
 * @property datetime $next_mail
 * @property datetime $last_mail
 * @property integer $citoyen_id
 * @property string $verif
 * @property Citoyen $Citoyen
 * 
 * @method string   getEmail()          Returns the current record's "email" value
 * @method string   getQuery()          Returns the current record's "query" value
 * @method string   getFilter()         Returns the current record's "filter" value
 * @method string   getQuery_md5()      Returns the current record's "query_md5" value
 * @method string   getTiTre()          Returns the current record's "titre" value
 * @method boolean  getConfirmed()      Returns the current record's "confirmed" value
 * @method boolean  getNo_humaN_query() Returns the current record's "no_human_query" value
 * @method enum     getPeriod()         Returns the current record's "period" value
 * @method datetime getNext_mail()      Returns the current record's "next_mail" value
 * @method datetime getLast_maiL()      Returns the current record's "last_mail" value
 * @method integer  getCitoyen_id()     Returns the current record's "citoyen_id" value
 * @method string   getVerif()          Returns the current record's "verif" value
 * @method Citoyen  getCitoyen()        Returns the current record's "Citoyen" value
 * @method Alerte   setEmail()          Sets the current record's "email" value
 * @method Alerte   setQuery()          Sets the current record's "query" value
 * @method Alerte   setFilter()         Sets the current record's "filter" value
 * @method Alerte   setQuery_md5()      Sets the current record's "query_md5" value
 * @method Alerte   setTiTre()          Sets the current record's "titre" value
 * @method Alerte   setConfirmed()      Sets the current record's "confirmed" value
 * @method Alerte   setNo_humaN_query() Sets the current record's "no_human_query" value
 * @method Alerte   setPeriod()         Sets the current record's "period" value
 * @method Alerte   setNext_mail()      Sets the current record's "next_mail" value
 * @method Alerte   setLast_maiL()      Sets the current record's "last_mail" value
 * @method Alerte   setCitoyen_id()     Sets the current record's "citoyen_id" value
 * @method Alerte   setVerif()          Sets the current record's "verif" value
 * @method Alerte   setCitoyen()        Sets the current record's "Citoyen" value
 * 
 * @package    senat
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAlerte extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('alerte');
        $this->hasColumn('email', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('query', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('filter', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('query_md5', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('titre', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('confirmed', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('no_human_query', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('period', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'HOUR',
              1 => 'DAY',
              2 => 'WEEK',
              3 => 'MONTH',
             ),
             ));
        $this->hasColumn('next_mail', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('last_mail', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('citoyen_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('verif', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));


        $this->index('index_uniq', array(
             'fields' => 
             array(
              0 => 'email',
              1 => 'citoyen_id',
              2 => 'query_md5',
             ),
             'type' => 'unique',
             ));
        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Citoyen', array(
             'local' => 'citoyen_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}