<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2009/07/01 13:11:08
return array(

  // sfProtoculousPlugin_module_libs

  // sfProtoculousPlugin_lib

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfFormFilterDoctrine' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfFormDoctrine' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfWebDebugPanelDoctrine' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfDoctrineCli' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfWidgetFormDoctrineChoice' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',
  'sfWidgetFormDoctrineChoiceMany' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoiceMany.class.php',
  'sfWidgetFormDoctrineSelectMany' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineSelectMany.class.php',
  'sfWidgetFormDoctrineSelect' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineSelect.class.php',
  'sfTesterDoctrine' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfValidatorDoctrineChoiceMany' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoiceMany.class.php',
  'sfDoctrineUniqueValidator' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/validator/sfDoctrineUniqueValidator.class.php',
  'sfValidatorDoctrineChoice' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfValidatorDoctrineUnique' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfDoctrineException' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfDoctrineFormFilterGenerator' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfDoctrineFormGenerator' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfDoctrineColumn' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfDoctrineGenerator' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'sfDoctrineRoute' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfDoctrineRouteCollection' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfDoctrineLogger' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/log/sfDoctrineLogger.class.php',
  'sfDoctrinePager' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfDoctrineConnectionListener' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfDoctrineDataRetriever' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDataRetriever.class.php',
  'sfDoctrineDatabase' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfDoctrineGenerateAdminTask' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfDoctrineBuildModelTask' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfDoctrineGenerateModuleTask' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfDoctrineBuildFormsTask' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfDoctrineBuildFiltersTask' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfDoctrineGenerateMigrationsDbTask' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfDoctrineMigrateTask' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sfDoctrineDumpDataTask' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfDoctrineDqlTask' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfDoctrineLoadDataTask' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfDoctrineInsertSqlTask' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfDoctrineBuildAllReloadTask' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildAllReloadTask.class.php',
  'sfDoctrineGenerateModuleForRouteTask' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfDoctrineBuildSchemaTask' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfDoctrineBuildSqlTask' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfDoctrineBuildDbTask' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfDoctrineDropDbTask' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfDoctrineBaseTask' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfDoctrineBuildAllReloadTestAllTask' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildAllReloadTestAllTask.class.php',
  'sfDoctrineBuildAllTask' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildAllTask.class.php',
  'sfDoctrineRebuildDbTask' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineRebuildDbTask.class.php',
  'sfDoctrineGenerateMigrationTask' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfDoctrineBuildAllLoadTask' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildAllLoadTask.class.php',
  'sfDoctrineGenerateMigrationsModelsTask' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfDoctrineRecordI18nFilter' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfDoctrineRecord' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfDoctrineRecordListener' => '/home/cpc/symfony-1.2.7/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordListener.class.php',

  // project

  // project_model

  // application
  'myUser' => '/home/cpc/project/apps/frontend/lib/myUser.class.php',

  // modules
);
