<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2009/07/01 13:11:09

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=my.cpc.tangui.eu.org;dbname=cpc',
  'username' => 'cpc',
  'password' => 'M_O_T__D_E__P_A_S_S_E',
  'name' => 'doctrine',
)),);
