<?php

/**
 * Alerte
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cpc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Alerte extends BaseAlerte
{
  public function getEmail() {
    if ($this->citoyen_id) {
      return $this->getCitoyen()->email;
    }
    return $this->_get('email');
  }

  public function generateVerif() {
    $v = md5(rand(1, 999999999999));
    $this->_set('verif', $v);
    return $v;
  }
  public function getTitre() {
    if (!$this->_get('titre'))
      return "Recherche correspondant aux mots clés « ".$this->query." »";
    return $this->_get('titre');
  }

   public function save(Doctrine_Connection $c = null) {
    if (!$this->last_mail)
      $this->last_mail = date('Y-m-d H:i:s');
    if (!$this->verif)
      $this->generateVerif();
    if ($this->citoyen_id)
      $this->confirmed = 1;
    $this->query_md5 = md5($this->query.$this->filter);
    return parent::save($c);
  }
}
