<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Alinea extends BaseAlinea
{

  public function getTitre() {
    return 'Article '.$this->getArticle()->titre.' alinéa '.$this->numero;
  }

  static $code_legif = array(
     "code de l'action sociale et des familles" => "LEGITEXT000006074069",
     "code de l'artisanat" => "LEGITEXT000006075116",
     "code des assurances" => "LEGITEXT000006073984",
     "code de l'aviation civile" => "LEGITEXT000006074234",
     "code du cinéma et de l'image animée" => "LEGITEXT000020908868",
     "code civil" => "LEGITEXT000006070721",
     "code de commerce" => "LEGITEXT000005634379",
     "code des communes de la Nouvelle-Calédonie" => "LEGITEXT000006070300",
     "code des communes" => "LEGITEXT000006070162",
     "code de la consommation" => "LEGITEXT000006069565",
     "code de la construction et de l'habitation" => "LEGITEXT000006074096",
     "code de la défense" => "LEGITEXT000006071307",
     "code de déontologie de la police nationale" => "LEGITEXT000006071071",
     "code de déontologie des agents de police municipale" => "LEGITEXT000006070159",
     "code de déontologie des architectes" => "LEGITEXT000006074232",
     "code de déontologie des professionnels de l'expertise comptable" => "LEGITEXT000006074510",
     "code disciplinaire et pénal de la marine marchande" => "LEGITEXT000006071188",
     "code du domaine de l'état et des collectivités publiques applicable à la collectivité territoriale de mayotte" => "LEGITEXT000006074235",
     "code du domaine de l'état" => "LEGITEXT000006070208",
     "code du domaine public fluvial et de la navigation intérieure" => "LEGITEXT000006074237",
     "code des douanes de mayotte" => "LEGITEXT000006071645",
     "code des douanes" => "LEGITEXT000006071570",
     "code de l'éducation" => "LEGITEXT000006071191",
     "code électoral" => "LEGITEXT000006070239",
     "code de l'entrée et du séjour des étrangers et du droit d'asile" => "LEGITEXT000006070158",
     "code de l'environnement" => "LEGITEXT000006074220",
     "code de l'expropriation pour cause d'utilité publique" => "LEGITEXT000006074224",
     "code de la famille et de l'aide sociale" => "LEGITEXT000006072637",
     "code forestier de mayotte" => "LEGITEXT000006071556",
     "code forestier" => "LEGITEXT000006071514",
     "code général de la propriété des personnes publiques" => "LEGITEXT000006070299",
     "code général des collectivités territoriales" => "LEGITEXT000006070633",
     "code général des impôts" => "LEGITEXT000006069577",
     "code général des impôts, annexe 1" => "LEGITEXT000006069568",
     "code général des impôts, annexe 2" => "LEGITEXT000006069569",
     "code général des impôts, annexe 3" => "LEGITEXT000006069574",
     "code général des impôts, annexe 4" => "LEGITEXT000006069576",
     "code général des impôts" => "LEGITEXT000006069577",
     "code de l'industrie cinématographique" => "LEGITEXT000006070882",
     "code des instruments monétaires et des médailles" => "LEGITEXT000006070666",
     "code des juridictions financières" => "LEGITEXT000006070249",
     "code de justice administrative" => "LEGITEXT000006070933",
     "code de justice militaire" => "LEGITEXT000006071360",
     "code de la légion d'honneur et de la médaille militaire" => "LEGITEXT000006071007",
     "livre des procédures fiscales" => "LEGITEXT000006069583",
     "code des marchés publics" => "LEGITEXT000005627819",
     "code minier" => "LEGITEXT000006071785",
     "code monétaire et financier" => "LEGITEXT000006072026",
     "code de la mutualité" => "LEGITEXT000006074067",
     "code de l'organisation judiciaire" => "LEGITEXT000006071164",
     "code du patrimoine" => "LEGITEXT000006074236",
     "code pénal" => "LEGITEXT000006070719",
     "code des pensions civiles et militaires de retraite" => "LEGITEXT000006070302",
     "code des pensions de retraite des marins français du commerce, de pêche ou de plaisance" => "LEGITEXT000006074066",
     "code des pensions militaires d'invalidité et des victimes de la guerre" => "LEGITEXT000006074068",
     "code des ports maritimes" => "LEGITEXT000006074233",
     "code des postes et des communications électroniques" => "LEGITEXT000006070987",
     "code de procédure civile" => "LEGITEXT000006070716",
     "code de procédure pénale" => "LEGITEXT000006071154",
     "code de la propriété intellectuelle" => "LEGITEXT000006069414",
     "code de la recherche" => "LEGITEXT000006071190",
     "code de la route" => "LEGITEXT000006074228",
     "code rural" => "LEGITEXT000006071367",
     "code de la santé publique" => "LEGITEXT000006072665",
     "code de la sécurité sociale" => "LEGITEXT000006073189",
     "code du service national" => "LEGITEXT000006071335",
     "code du sport" => "LEGITEXT000006071318",
     "code du tourisme" => "LEGITEXT000006074073",
     "code du travail applicable à mayotte" => "LEGITEXT000006072052",
     "code du travail maritime" => "LEGITEXT000006072051",
     "code du travail" => "LEGITEXT000006072050",
     "code de l'urbanisme" => "LEGITEXT000006074075",
     "code de la voirie routière" => "LEGITEXT000006070667"
    );

  public function setTexteCode($texte, $refcode = '') {
    $this->texte = $texte;
    $texte = strtolower(preg_replace('/\<\/?[a-z]+\>/i', '', $texte));
    $texte = trim(preg_replace('/\s+/', ' ', $texte));
    foreach (self::$code_legif as $code => $legif) if (preg_match('/'.$code.'/', $texte)) {
      $this->ref_loi = $code;
      return $code;
    }
    if (preg_match('/(loi\sn°\s?[\d\-]+\sdu\s\d+e?r?\s[a-zéû]+\s\d{4})/', $texte, $match)) {
      $this->ref_loi = $match[1];
      return $match[1];
    }
    if ($refcode != '') {
      $this->ref_loi = $refcode;
      return $refcode;
    }
    return '';
  }

}
