<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Alinea extends BaseAlinea
{

  public function getTitre() {
    return 'Article '.$this->getArticle()->numero.' alinéa '.$this->numero;
  }

}
