<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AmendementTable extends Doctrine_Table
{

  public function findOneByLegisLoiNumRect($legis, $loi, $numero, $rect) {
    $query = $this->createQuery('a')
      ->where('a.legislature = ?', $legis)
      ->andWhere('a.texteloi_id = ?', $loi)
      ->andWhere('a.numero = ?', $numero)
      ->andWhere('a.rectif = ?', $rect);
    return $query->fetchOne();
  }

  public function findByCleanedSource($source) {
    $query = $this->createQuery('a');
    if (strpos($source, '/AN/') !== false) {
      $source2 = preg_replace('/\/AN\//', '/', $source);
      $query->whereIn('a.source', array($source, $source2));
    } else {
      $query->where('a.source = ?', $source);
    }
    return $query->execute();
  }

}
