<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Amendement extends BaseAmendement {
    public function setAuteurs($auteurs) {
      $debug = false;
      if ($debug) $save = sprintf($auteurs);
      $groupe = null;
      $sexe = null;
      if ($debug) print "0: ".$auteurs."\n";
      $auteurs = preg_replace('/^\s*,\s*/', '', $auteurs);
      $auteurs = preg_replace('/,\s*$/', '', $auteurs);
      $auteurs = preg_replace('/\s+Mme,\s*/', ' Mme ', $auteurs);
      $auteurs = preg_replace('/([a-z])\s+(M[\.Mml])/', '\1, \2', $auteurs, -1, $ct);
      $auteurs = preg_replace('/\s*([rR]apporteur.*),\s*M/', ', M',$auteurs, -1, $ct);
      $auteurs = preg_replace('/\s*([rR]apporteur.*)/', ', M',$auteurs, -1, $ct);
      if ($ct >= 1 && $debug) print "1: ".$auteurs."\n";
      if ($ct >= 1 && $debug) print "2: ".$auteurs."\n";
      $auteurs = preg_replace('/M\./', 'M ', $auteurs, -1, $ct);
      if ($ct >= 1 && $debug) print "3: ".$auteurs."\n";
      $auteurs = preg_replace('/(,\s*)+,/', ',', $auteurs, -1, $ct);
      if ($debug) print "4: ".$auteurs." // ".$groupe."\n";
      if (preg_match('/^\s*(.*),\s*les\s+.*\s+[gG]roupe\s+(.*)\s*$/' ,$auteurs, $match)) {
        $auteurs = $match[1];
        $groupe = preg_replace('/\s*de\s+la\s*/', '', $match[2]);
        if ($debug) print "4: ".$auteurs." // ".$groupe."\n";
      }
      $arr = preg_split('/,/', $auteurs);
      foreach ($arr as $depute) {
        $bool = false;
        if (preg_match('/^\s*(M+[\s\.ml]{1})[a-z]*\s*([dA-Z\s].*)\s*$/', $depute, $match)) {
          $nom = $match[2];
          if (preg_match('/M[ml]/', $match[1]))
            $sexe = 'F';
          else $sexe = 'H';
          $bool = $this->addParlementaireByNom($nom, $sexe, $groupe, $debug);
        } else if (preg_match('/gouvernement/i', $depute)) {
          if ($debug) print "5: "."  ".$depute."\n";
        } else $bool = $this->addParlementaireByNom($depute, $sexe, $groupe, $debug);
    //    if (!$bool && $debug) print "6: "."  source : ".$save."\n";
      }
    }

    public function addParlementaireByNom($nom, $sexe, $groupe, $debug) {
        if ($debug) print "5: "."  ".$nom." // ".$sexe." // ".$groupe."\n";
        $memeNom = Doctrine::getTable('Parlementaire')->findByNom($nom);
        if (count($memeNom) == 0) {
            $memeNom = Doctrine::getTable('Parlementaire')->findByNomDeFamille($nom);
        }
        if (count($memeNom) == 0) {
            $depute = Doctrine::getTable('Parlementaire')->similarTo($nom);
        }
        else if (count($memeNom) == 1) {
            $depute = $memeNom[0];
        }
        else if ($sexe) foreach ($memeNom as $de) {
         //   print $de->nom." ".$de->sexe.' '.$de->nom_de_famille." ; ";
            if ($de->sexe == $sexe) {
                if (!$depute) $depute = $de;
                else {
                  unset($memenom);
                  print "ERROR: Plusieurs députés de meme sexe et nom : ".$nom." sexe: ".$sexe." groupe: ".$groupe."\n";
                  // try to find by groupe, if groupe unset try with previous auteurs ex: Cochet amdmt 1630 69, 7_28.txt
                  return false;
                }
            }
        }
        unset($memenom);
        if (!$depute) {
             print "ERROR json: Auteur d'amendement inconnu : ".$nom." sexe: ".$sexe." groupe: ".$groupe."\n";
             return false;
        }
        foreach($this->getParlementaires() as $par) {
          if ($par == $depute)
            $depute->free();
            return true;
          }
        $pa = new ParlementaireAmendement();
        $pa->_set('Parlementaire', $depute);
        $pa->_set('Amendement', $this);
        $depute->free();
        return $pa->save();
    }

    public function setSort($sort) {
// parse sort to fit enum
    }
}