<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AmendementTable extends Doctrine_Table
{

  public function findLastOneByLegisLoiNum($legis, $loi, $numero) {
    $lois = array($loi);
    if (substr($loi, 0, 2) == "TA") {
      $lois[] = str_replace("TA", "TA0", $loi);
      $lois[] = str_replace("TA", "TA00", $loi);
      $lois[] = str_replace("TA", "TA000", $loi);
      $lois[] = str_replace("TA000", "TA", $loi);
      $lois[] = str_replace("TA00", "TA", $loi);
      $lois[] = str_replace("TA0", "TA", $loi);
    }
    $query = $this->createQuery('a')
      ->where('a.legislature = ?', $legis)
      ->andWhereIn('a.texteloi_id', $lois)
      ->andWhere('a.numero = ?', $numero)
      ->andWhere('a.sort != ?', "Rectifié");
    return $query->fetchOne();
  }

  public function findOneByLegisLoiNumRect($legis, $loi, $numero, $rect) {
    $query = $this->createQuery('a')
      ->where('a.legislature = ?', $legis)
      ->andWhere('a.texteloi_id = ?', $loi)
      ->andWhere('a.numero = ?', $numero)
      ->andWhere('a.rectif = ?', $rect);
    return $query->fetchOne();
  }

  public function findByCleanedSource($source) {
    $query = $this->createQuery('a');
    if (strpos($source, '/AN/') !== false) {
      $source2 = preg_replace('/\/AN\//', '/', $source);
      $query->whereIn('a.source', array($source, $source2));
    } else {
      $query->where('a.source = ?', $source);
    }
    return $query->execute();
  }

}
