<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AmendementTable extends Doctrine_Table
{

  public function findOneByLegisLoiNumRect($legis, $loi, $numero, $rect) {
    $query = $this->createQuery('a')
      ->where('a.legislature = ?', $legis)
      ->andWhere('a.texteloi_id = ?', $loi)
      ->andWhere('a.numero = ?', $numero)
      ->andWhere('a.rectif = ?', $rect);
    return $query->fetchOne();
  }


}
