<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArticleLoiTable extends Doctrine_Table
{

  public function findOneByLoiSlug($loi, $slug) {
    $query = $this->createQuery('a')
      ->where('a.texteloi_id = ?', $loi)
      ->andWhere('a.slug = ?', $slug);
    return $query->fetchOne();
  }

  public function findOneByLoiTitre($loi, $titre) {
    $query = $this->createQuery('a')
      ->where('a.texteloi_id = ?', $loi)
      ->andWhere('a.titre = ?', $titre);
    return $query->fetchOne();
  }

  public function findOrCreate($loi, $article, $chapitre = 0, $section = 0) {
    $art = $this->findOneByLoiTitre($loi, $article);
    if (!$art) {
      $art = new ArticleLoi();
      $art->texteloi_id = $loi;
      $art->titre = $article;
      $art->ordre = 0;
      $loiobj = Doctrine::getTable('TitreLoi')->findLoiOrCreate($loi);
      $loiobj->nb_articles += 1;
      $loiobj->save();
      if ($chapitre != 0) {
        $chap = Doctrine::getTable('TitreLoi')->findChapitreOrCreate($loi, $chapitre);
        $chap->nb_articles += 1;
        $chap->save();
        if ($section != 0) {
          $sec = Doctrine::getTable('TitreLoi')->findSectionOrCreate($loi, $chapitre, $section);
          $sec->nb_articles++;
          $art->setTitreLoi($sec);
          $sec->save();
        } else {
          $art->setTitreLoi($chap);
        }
      } else {
        $art->setTitreLoi($loiobj);
      }
      $art->save();
    }
    return $art;
  }

}
