<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArticleLoiTable extends Doctrine_Table
{

  public function findOneByLoiSlug($loi, $slug) {
    $query = $this->createQuery('a')
      ->where('a.texteloi_id = ?', $loi)
      ->andWhere('a.slug = ?', $slug);
    return $query->fetchOne();
  }

  public function findOneByLoiTitre($loi, $titre) {
    $query = $this->createQuery('a')
      ->where('a.texteloi_id = ?', $loi)
      ->andWhere('a.titre = ?', $titre);
    return $query->fetchOne();
  }

  private static function getArticleTitreLoi($loi, $levels = array(0, 0, 0, 0)) {
    $titreloi = $loi;
    for ($i = 0; $i < 4; $i++) {
      if ($levels[$i] != 0) {
        $par = Doctrine::getTable('TitreLoi')->findLevelOrCreate($loi->texteloi_id, $i+1, $levels);
        $par->nb_articles += 1;
        $par->save();
        $titreloi = $par;
      } else return $titreloi;
    }
    return $titreloi;
  }

  public function findOrCreate($loi, $article, $levels = array(0, 0, 0, 0)) {
    $art = $this->findOneByLoiTitre($loi, $article);
    if (!$art) {
      $art = new ArticleLoi();
      $art->texteloi_id = $loi;
      $art->titre = $article;
      $art->ordre = 0;
      $loiobj = Doctrine::getTable('TitreLoi')->findLoiOrCreate($loi);
      $loiobj->nb_articles += 1;
      $loiobj->save();
      $art->setTitreLoi(self::getArticleTitreLoi($loiobj, $levels));
      $art->save();
    }
    return $art;
  }

}
