<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CitoyenTable extends Doctrine_Table
{
  public function getPager($request, $query = NULL) {
    $pager = new sfDoctrinePager('Citoyen', 24);
    $pager->setQuery($query);
    $pager->setPage($request->getParameter('page', 1));
    $pager->init();
    return $pager;
  }
}
