<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CommentaireObjectTable extends Doctrine_Table
{

  public function findUnique($object_type, $object_id, $comment_id) {
    return $this->createQuery('c')
      ->where('c.object_type = ?', $object_type)
      ->andWhere('c.object_id = ?', $object_id)
      ->andWhere('c.commentaire_id = ?', $comment_id)
      ->fetchOne();
  }

  public function findUniqueOrCreate($object_type, $object_id, $comment_id) {
    if (!($this->findUnique($object_type, $object_id, $comment_id))) {  
      $co = new CommentaireObject();
      $co->object_type = $object_type;
      $co->object_id = $object_id;
      $co->commentaire_id = $comment_id;
      $co->save();
    }
  }

  public function getParlementaires($commentaire_id) {
    $pids = $this->createQuery('c')->select('object_id')->where('object_type = "Parlementaire"')->andWhere('commentaire_id = ?', $commentaire_id)->fetchArray();
    $ids = array();
    foreach ($pids as $id) {
      array_push($ids, $id['object_id']);
    }
    if (count($ids))
      return Doctrine::getTable('Parlementaire')->createQuery('p')->whereIn('p.id', $ids)->execute();
    return ;
  }
}
