<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Commentaire extends BaseCommentaire
{
  protected static $mois = array('01'=>'janvier', '02'=>'février', '03'=>'mars', '04'=>'avril', '05'=>'mai', '06'=>'juin', '07'=>'juillet', '08'=>'août', '09'=>'septembre', '10'=>'octobre', '11'=>'novembre', '12'=>'décembre');
  public static function cleanCommentaire($s) {
    $s = preg_replace('/<[^>]+>/', '', $s);
    $s = preg_replace('/(http\S+)/', '<a rel="nofollow" href="\\1">\\1</a>', $s);
    $s = '<p>'.$s.'</p>'; 
    $s = preg_replace('/\n/', '</p><p>', $s);
    return $s;
  }
  public function addParlementaire($parlementaire_id) {
    if (!$this->id) {
      throw new Exception('no commentaire id');
    }
    $cp = new CommentaireParlementaires();
    $cp->parlementaire_id = $parlementaire_id;
    $cp->commentaire_id = $this->id;
    $cp->save();
  }
  public function getHumainDateTime() {
    $time = strtotime($this->created_at);
    return date('j ',$time).self::$mois[date('m', $time)].date(' Y à G:i', $time);
  }
  public function getHumainUser() {
    if (!$this->citoyen_id)
      return 'Anonyme';
    return '';
  }
}
