<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Intervention extends BaseIntervention
{
  public function setSeance($type, $date, $heure, $session, $commission = null) {
    $this->setType($type);
    if ($type == 'commission') {
      $commission = Doctrine::getTable('Organisme')->findOneByNomOrCreateIt($commission, 'parlementaire');
      $seance = $commission->getSeanceByDateAndMomentOrCreateIt($date, $heure, $session);
    }else{
      $seance = Doctrine::getTable('Seance')->findOneOrCreateIt('hemicycle', $date, $heure, $session);
    }
    return $this->_set('seance_id', $seance->id);
  }
  public function setPersonnaliteByNom($nom, $fonction = null) 
  {
    $personne = Doctrine::getTable('Parlementaire')->findOneByNom($nom);
    if (!$personne) {
      $personne = Doctrine::getTable('Parlementaire')->similarTo($nom);
    }
    if ($personne) {
      return $this->setParlementaire($personne, $fonction);
    }
    $personne = Doctrine::getTable('Personnalite')->findOneByNom($nom);
    if (!$personne) {
      $personne = Doctrine::getTable('Personnalite')->similarTo($nom);
    }
    if (!$personne) {
      $personne = new Personnalite();
      $personne->setNom($nom);
      $personne->save();
    }
    if ($personne) {
      return $this->setPersonnalite($personne,$fonction);
    }
  }
  public function setParlementaire($parlementaire, $fonction = null) {
    foreach($this->getParlementaires() as $par) {
      if ($par == $parlementaire)
	return false;
    }
    $ip = new PersonnaliteIntervention();
    $ip->setParlementaire($parlementaire);
    $ip->setIntervention($this);
    if ($fonction)
      $ip->setFonction($fonction);
    $this->getSeance()->addPresence($parlementaire, 'intervention', $this->source);
    return $ip->save();
  }
  public function setPersonnalite($perso, $fonction = null) {
    foreach($this->getPersonnalites() as $per) {
      if ($per == $perso)
	return false;
    }
    $ip = new PersonnaliteIntervention();
    $ip->setPersonnalite($perso);
    $ip->setIntervention($this);
    if ($fonction)
      $ip->setFonction($fonction);
    return $ip->save();
  }
  public function getAllPersonnalitesAndFonctions() {
    $pis = $this->getPersonnaliteInterventions();
    $res = array();
    foreach($pis as $pi){
      $p = $pi->getParlementaire();
      if (!$p) 
	$p = $pi->getPersonnalite();
      array_push($res, array($p, $pi->fonction));
    }
    return $res;
  }
  public function setContexte($context) {
    return $this->setSection(doctrine::getTable('Section')->findOneByContexteOrCreateIt($context));
  }
  public function setAmendements($tamendements) {
    $tamendements = preg_replace('/[^,\d]+/', '', $tamendements);
    $amends = preg_split('/\s*,\s*/', $tamendements);
    foreach($amends as $amend) {
      $tag = 'loi:amendement='.$amend;
      $this->addTag($tag);
      //      $this->getSection()->addTag('amendement:'.$amend);
    }
  }
  public function setLois($tlois) {
    $tlois = preg_replace('/[^,\d]+/', '', $tlois);
    $lois = preg_split('/\s*,\s*/', $tlois);
    foreach($lois as $loi) {
      $tag = 'loi:numero='.$loi;
      $this->addTag($tag);
      //      $this->getSection()->addTag('loi:'.$loi);
    }
  }

}