<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Intervention extends BaseIntervention
{
  public function setSeance($commission, $date, $heure) {
    $commission = Doctrine::getTable('Organisme')->findOneByNomOrCreateIt(strtolower($commission), 'parlementaire');
    $seance = $commission->getSeanceByDateAndMomentOrCreateIt($date, $heure);
    return $this->_set('seance_id', $seance->id);
  }
  public function setPersonnaliteByNom($nom) 
  {
    $personne = Doctrine::getTable('Parlementaire')->findOneByNom($nom);
    if (!$personne) {
      $personne = Doctrine::getTable('Parlementaire')->similarTo($nom);
    }
    if ($personne) {
      return $this->parlementaire = $personne;
    }
    $personne = Doctrine::getTable('Personnalite')->findOneByNom($nom);
    if (!$personne) {
      $personne = Doctrine::getTable('Personnalite')->similarTo($nom);
    }
    if ($personne) {
      return $this->personnalite = $personne;
    }
  }
  public function setParlementaire($parlementaire) {
    foreach($this->getParlementaires() as $par) {
      if ($par == $parlementaire)
	return false;
    }
    $ip = new PersonnaliteIntervention();
    $ip->setParlementaire($parlementaire);
    $ip->setIntervention($this);
    $this->getSeance()->addPresence($parlementaire, 'intervention', $this->source);
    return $ip->save();
  }
  public function setPersonnalite($perso) {
    foreach($this->getPersonnalites() as $per) {
      if ($per == $perso)
	return false;
    }
    $ip = new PersonnaliteIntervention();
    $ip->setPersonnalite($perso);
    $ip->setIntervention($this);
    return $ip->save();
  }
  public function getAllPersonnalites() {
    $p = $this->getParlementaires();
    return $p;
  }

}