<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ObjectCommentable extends BaseObjectCommentable
{
  //Sometimes the comment is not saved, we need to simulate it with $inc
  public function updateNbCommentaires($inc = 0) {
    $res = Doctrine::getTable('Commentaire')->createQuery('c')
      ->select('count(*) as nb')
      ->where('object_type = ?', get_class($this))
      ->andWhere('object_id = ?', $this->id)
      ->andWhere('is_public = ?', 1)
      ->fetchArray();
    if (isset($res[0]['nb']))
      $this->nb_commentaires = $res[0]['nb'] + $inc;
  }
}
