<?php

require_once "myTools.class.php";

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Organisme extends BaseOrganisme
{
  public function getSmallNomGroupe() {
    $hashmap = array(
        "union pour un mouvement populaire" => "UMP",
        "socialiste, radical, citoyen et divers gauche" => "SRC",
        "gauche démocrate et républicaine" => "GDR",
        "députés n'appartenant à aucun groupe" => "NI",
        "nouveau centre" => "NC"
    );
    return $hashmap[$this->getNom()];
  }

  public function getSeancesByDateAndNom($date, $nom) {
    $q = Doctrine::getTable('Seance')->createQuery('s')->where("organisme_id = ?", $this->id)->andWhere('date = ?', $date)->andWhere('nom = ?', $nom);
    return $q->execute()->getFirst();
  }
}