<?php

require_once "myTools.class.php";

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Organisme extends BaseOrganisme
{
  public function __tostring() {
    return substr($this->nom, 0, 100);
  }
  public function getSmallNomGroupe() {
    $hashmap = array(
        "Union pour un mouvement populaire" => "UMP",
        "Socialiste, radical, citoyen et divers gauche" => "SRC",
        "Gauche démocrate et républicaine" => "GDR",
        "Députés n'appartenant à aucun groupe" => "NI",
        "Nouveau centre" => "NC"
    );
    return $hashmap[$this->getNom()];
  }
  public static function getNomByAcro($acro) {
    $acro = strtolower($acro);
    if (preg_match('/^(ump|src|gdr|ni|nc)$/i', $acro)) {
      $hashmap = array(
         "ump" => "Union pour un mouvement populaire",
         "src" => "Socialiste, radical, citoyen et divers gauche",
         "gdr" => "Gauche démocrate et républicaine",
         "ni" => "Députés n'appartenant à aucun groupe",
         "nc" => "Nouveau centre" );
      return $hashmap["$acro"];
    } else {
      return false;
    }
  }
  public function getSeanceByDateAndMomentOrCreateIt($date, $moment, $session = null) {
    $seance = $this->getSeanceByDateAndMoment($date, $moment);
    if (!$seance) {
      $seance = new Seance();
      $seance->type = 'commission';
      $seance->setDate($date);
      $seance->moment = Seance::convertMoment($moment);
      $seance->Organisme = $this;
      $seance->setSession($session);
      $seance->save();
    }
    return $seance;
  }

  public function getNom() {
    $nom = $this->_get('nom');
    $nom = ucfirst($nom);
    return $nom;
  }

  public function getSeanceByDateAndMoment($date, $moment) {
    $moment = Seance::convertMoment($moment);
    $q = Doctrine::getTable('Seance')->createQuery('s');
    $q->where("organisme_id = ?", $this->id)->andWhere('date = ?', $date)->andWhere('moment = ?', $moment);
    $res = $q->fetchOne();
    $q->free();
    unset($q);
    if ($res) {
      return $res;
    }
    $q = Doctrine::getTable('Seance')->createQuery('s');
    $q->where("organisme_id = ?", $this->id)->andWhere('date = ?', $date);
    if (count($q->fetchArray()) && preg_match('/(\d+)[:](\d+)/', $moment, $match)) {
      $q = Doctrine::getTable('Seance')->createQuery('s');
      $q->where("organisme_id = ?", $this->id)->andWhere('date = ?', $date)->andWhere('moment LIKE ?', $match[1].':%');
      $res = $q->fetchOne();
      $q->free();
      unset($q);
    }
    return $res;
  }
}