<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrganismeTable extends Doctrine_Table
{
  public function findOneByNomOrCreateIt($nom, $type) {
    $nom = strtolower($nom);
    $nom = preg_replace('/&#8217;/', '’', $nom);
    echo "-$nom-\n";
    $org = $this->findOneByNom($nom);
    if (!$org) {
      $org = new Organisme();
      $org->type = $type;
      $org->nom = $nom;
      $org->save();
    }
    return $org;
  }
}