<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ParlementaireTable extends PersonnaliteTable
{
  static $all = null;
  public function similarTo($str)
  {
    $str = preg_replace('/\(.*\)/', '', $str);

    //load parlementaires only once
    if ($all == null) {
      $all = $this->createQuery('p')->execute();
    }
    $closest = null;
    $closest_res = -1;
    //Compare each parlementaire with the string and keep the best
    foreach ($all as $parl) {
      $res = similar_text(preg_replace('/[^a-z]/i', ' ', $str), preg_replace('/[^a-z]/i', ' ', $parl->nom), $pc);
      if ($res > 0 && $pc > $closest_res) {
	$closest = $parl;
	$closest_res = $pc;
      }
    }
    //If more than 90% similarities, it is the best
    if ($closest_res > 90)
      return $closest;
    //If str is the end of the best parlementaire, it is OK
    if (preg_match('/'.preg_replace('/[^a-z]/i', '', $str).'$/', $closest->nom))
      return $closest;

    return null;
  }

  public function getPager($request, $query = NULL)
  {
    $pager = new sfDoctrinePager('Parlementaire',20);
    if (!$query) {
      $query = $this->createQuery('p')->orderBy('p.nom_de_famille ASC');
    }
    $pager->setQuery($query);
    $pager->setPage($request->getParameter('page', 1));
    $pager->init();
    return $pager;
  }
}