<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ParlementaireAmendement extends BaseParlementaireAmendement
{
  public function getGroupeAcronyme() {
    return myTools::getObjectGroupeAcronyme($this);
  }
}
