<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Parlementaire extends BaseParlementaire
{
	public function setNom($str) {
	       $perma = strtolower($str);
	       $perma = preg_replace('/[éèêë]+/', 'e', $perma);
	       $perma = preg_replace('/[à]+/', 'a', $perma);
	       $perma = preg_replace('/[ç]+/', 'c', $perma);
	       $perma = preg_replace('/[ù]+/', 'u', $perma);
	       $perma = preg_replace('/\W/', '-', $perma);
	       $this->_set('permalink', $perma);
	       return $this->_set('nom', $str);
	}
	public function setCirconscription($str) {
	       if (preg_match('/(.*)\((\d+)/', $str, $match)) {
	       	  $this->nom_circo = $match[1];
		  $this->num_circo = $match[2];
	       }
	}
	public function setDebutMandat($str) {
	       if (preg_match('/(\d{2})\/(\d{2})\/(\d{4})/', $str, $m)) {
	       	  $this->_set('debut_mandat', $m[3].'-'.$m[2].'-'.$m[1]);
	       }
	}
}