<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ParlementaireOrganisme extends BaseParlementaireOrganisme
{
  public function getNom() {
    if ($this->getType() == 'groupe') return $this->getOrganisme()->getSmallNomGroupe();
    else return $this->getOrganisme()->getNom();
  }
  public function getType() {
    return $this->getOrganisme()->getType();
  }
  public function getSlug() {
    return $this->getOrganisme()->getSlug();
  }
}