<?php

require_once "myTools.class.php";

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Parlementaire extends BaseParlementaire
{

  public function setNom($str) {
    if (preg_match('/^\S+ [a-z\s\']*([A-Z].+)/', $str, $match)) {
      $this->_set('nom_de_famille', $match[1]);
    }
    return $this->_set('nom', $str);
  }

  public function getCirconscription() {
    return $this->nom_circo."(".$this->num_circo.")";
  }

  public function setCirconscription($str) {
    if (preg_match('/(.*)\((\d+)/', $str, $match)) {
      $this->nom_circo = $match[1];
      $this->num_circo = $match[2];
    }
  }

  public function setDebutMandat($str) {
    if (preg_match('/(\d{2})\/(\d{2})\/(\d{4})/', $str, $m)) {
      $this->_set('debut_mandat', $m[3].'-'.$m[2].'-'.$m[1]);
    }
  }
  public function setFonctions($array) {
    return $this->setPOrganisme('parlementaire', $array);
  }
  public function setExtras($array) {
    return $this->setPOrganisme('extra', $array);
  }
  public function setGroupe($array) {
    return $this->setPOrganisme('groupe', $array);
  }

  public function setPOrganisme($type, $array) {
    $orgas = $this->getParlementaireOrganismes();
    foreach ($array as $item) {
      $args = preg_split('/\s+\/\s*/', $item);
      $orga = Doctrine::getTable('Organisme')->findOneByNom($args[0]);
      if (!$orga) {
	$orga = new Organisme();
	$orga->nom = $args[0];
	$orga->type = $type;
	$orga->save();
      }
      $po = new ParlementaireOrganisme();
      $po->setParlementaire($this);
      $po->setOrganisme($orga);
      $po->setFonction($args[1]);
      /*      if (isset($args[2])) {
	$po->setDebutFonction($args[2]);
	}*/
      $orgas->add($po);
    }
    $this->_set('ParlementaireOrganismes', $orgas);
  }
  public function setAutresmandats($array) {

  }
  public function setMails($array) {
  }
  public function setAdresses($array) {
  }
  public function getGroupe() {
    foreach($this->getParlementaireOrganismes() as $po) {
      if ($po->type == 'groupe') 
	return $po;
    }
  }
  public function getExtras() {
    $res = array();
    foreach($this->getParlementaireOrganismes() as $po) {
      if ($po->type == 'extra') 
	array_push($res, $po);
    }
    return $res;
  }
  public function getResponsabilites() {
    $res = array();
    foreach($this->getParlementaireOrganismes() as $po) {
      if ($po->type == 'parlementaire') 
	array_push($res, $po);
    }
    return $res;
  }
}