<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Personnalite extends BasePersonnalite
{
  /*  public function save(Doctrine_Connection $conn = null) {
    Doctrinue::getTable('Personnalite')->hasChanged();
    return parent::save($conn);
    }*/
  public function getLink() {
    return "";
  }
  public function getPhoto() {
    return "";
  }
}