<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Presence extends BasePresence
{
  public function addPreuve($type, $source) {
    $q = Doctrine::getTable('PreuvePresence')->createQuery('p');
    $preuve = $q->where('presence_id = ?', $this->id)->andWhere('type = ?', $type)->fetchOne();
    $q->free();
    if (!$preuve) {
      $preuve = new PreuvePresence();
      $preuve->presence_id = $this->id;
      $preuve->type = $type;
    }
    $preuve->source = $source;
    $res = $preuve->save();
    $preuve->free();
    return $res;
  }
}