<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Presence extends BasePresence
{
  public function addPreuve($type, $source) {
    $p = Doctrine::getTable('Presence');
    $q = Doctrine::getTable('PreuvePresence');
    $preuve = $q->createQuery('p')->where('presence_id = ?', $this->id)->andWhere('type = ?', $type)->execute()->getFirst();
    if (!$preuve) {
      $preuve = new PreuvePresence();
      $preuve->presence_id = $this->id;
      $preuve->type = $type;
    }
    $preuve->source = $source;
    return $preuve->save();
  }
}