<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Seance extends BaseSeance
{
  public function setSession($session) {
    return $this->_set('session', $session);
  }
  public function addPresence($parlementaire, $type, $source) {
    $q = Doctrine::getTable('Presence')->createQuery('p');
    $q->where('parlementaire_id = ?', $parlementaire->id)->andWhere('seance_id = ?', $this->id);
    $presence = $q->execute()->getFirst();
    $q->free();
    unset($q);
    if (!$presence) {
      $presence = new Presence();
      $presence->Parlementaire = $parlementaire;
      $presence->Seance = $this;
      $presence->date = $this->date;
      $presence->save();
    }
    $res = $presence->addPreuve($type, $source);
    $presence->free();
    return $res;
  }
  
  public static function convertMoment($moment) {
    if (preg_match('`(seance|séance)`i', $moment)) {
        if (preg_match('`1`', $moment)) return "1ère séance";
        if (preg_match('`(\d{1})`', $moment, $match)) return $match[1];
        return $moment;
    }
    if (preg_match('`(reunion|réunion)`i', $moment)) {
        if (preg_match('`1`', $moment)) return "1ère réunion";
        if (preg_match('`(\d{1})`', $moment, $match)) return $match[1]."ème réunion";
        return $moment;
    }
    if (preg_match('/(\d{1,2})[:h](\d{2})/', $moment, $match)) {
      $moment = sprintf("%02d:%02d", $match[1], $match[2]);
      return $moment;
    }
    return $moment;
  }
  
  public function setDate($date) {
    if (!$this->_set('date', $date))
      return false;
    $date = strtotime($date);
    $annee = date('Y', $date);
    $semaine = date('W', $date);
    if ($semaine == 53) {
      $annee++;
      $semaine = 1;
    }
    $this->_set('annee', $annee);
    $this->_set('numero_semaine', $semaine);
    return true;
  }
  public function getInterventions() {
    $q = doctrine::getTable('Intervention')->createQuery('i')->where('seance_id = ?', $this->id)->leftJoin('i.Personnalites p')->leftJoin('i.Parlementaires pa')->orderBy('i.timestamp ASC');
    return $q->execute();
  }
  public function getTableMatiere() {
    $q = Doctrine_Query::create()->select('s.titre, s.id, s.section_id')->from('Section s')->leftJoin('s.Interventions i')->where('i.seance_id = ?', $this->id)->orderBy('i.timestamp ASC');
    return $q->fetchArray();
  }
}