<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SeanceTable extends Doctrine_Table
{
  public function findOneOrCreateIt($type, $date, $heure, $session) {
    $s = $this->createQuery('s')->where('type = ?', $type)->andWhere('date = ?', $date)->andWhere('moment = ?', $heure)->fetchOne();
    if (!$s) {
      if ($type != 'hemicycle')
	return new Exception("Cannot create seance of type $type");
      $s = new Seance();
      $s->type = $type;
      $s->date = $date;
      $s->moment = $heure;
      $s->setSession($session);
      $s->save();
    }
    return $s;
  }

  public function getPager($request, $query = NULL)
  {
    $pager = new sfDoctrinePager('Seance',30);
    $pager->setQuery($query);
    $pager->setPage($request->getParameter('pages', 1));
    $pager->init();
    return $pager;
  }

}
