<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Seance extends BaseSeance
{
  public function addPresence($parlementaire, $type, $source) {
    $presence = Doctrine::getTable('Presence')->createQuery('p')->where('parlementaire_id = ?', $parlementaire->id)->andWhere('seance_id = ?', $this->id)->execute()->getFirst();
    if (!$presence) {
      $presence = new Presence();
      $presence->Parlementaire = $parlementaire;
      $presence->Seance = $this;
      $presence->save();
    }
    return $presence->addPreuve($type, $source);
  }
}