<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SeanceTable extends Doctrine_Table
{
  public function getFromSeanceArgs($type, $date, $heure, $session, $commission = null) {
    if ($type == 'commission') {
      $commission = Doctrine::getTable('Organisme')->findOneByNomOrCreateIt($commission, 'parlementaire');
      return $commission->getSeanceByDateAndMoment($date, $heure, $session);
    } 
    return $this->findOneByTypeDateHeureSession('hemicycle', $date, $heure, $session);
  }

  public function getOrCreateItFromSeanceArgs($type, $date, $heure, $session, $commission = null) {
    if ($type == 'commission') {
      $commission = Doctrine::getTable('Organisme')->findOneByNomOrCreateIt($commission, 'parlementaire');
      return $commission->getSeanceByDateAndMomentOrCreateIt($date, $heure, $session);
    } 
    return $this->findOneOrCreateIt('hemicycle', $date, $heure, $session);
  }

  public function findOneByTypeDateHeureSession($type, $date, $heure, $session) {
    return $this->createQuery('s')->where('type = ?', $type)->andWhere('date = ?', $date)->andWhere('moment = ?', $heure)->fetchOne();
  }

  public function findOneOrCreateIt($type, $date, $heure, $session) {
    $s = $this->findOneByTypeDateHeureSession($type, $date, $heure, $session);
    if (!$s) {
      if ($type != 'hemicycle')
	return new Exception("Cannot create seance of type $type");
      $s = new Seance();
      $s->type = $type;
      $s->date = $date;
      $s->moment = $heure;
      $s->setSession($session);
      $s->save();
    }
    return $s;
  }

  public function getPager($request, $query = NULL)
  {
    $pager = new sfDoctrinePager('Seance',30);
    $pager->setQuery($query);
    $pager->setPage($request->getParameter('pages', 1));
    $pager->init();
    return $pager;
  }

}
