<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SectionTable extends Doctrine_Table
{
  public function findOneByContexteOrCreateIt($contexte) {
    $contexte = preg_replace('/[\/\|\)\(]/', '', $contexte);
    $section = $this->find(md5($contexte));
    if ($section)
      return $section;
    $section = new Section();
    $section->setTitreComplet($contexte);
    $section->save();
    return $section;
  }
}