<?php

/**
 * TexteLoi
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cpc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TexteLoi extends BaseTexteLoi
{

  public function getAmendements() {
    if (!preg_match('/(Projet de loi|Proposition de loi|Proposition de résolution|Texte de la commission)/', $this->type))
      return 0;
    $res = count(Doctrine::getTable('Amendement')->createQuery('a')
      ->where('texteloi_id = ?', $this->numero)
      ->fetchArray());
    return $res;
  }

  public function getDossier() {
    $section = Doctrine::getTable('Section')->findOneByUrlAn($this->url_an);
    if (!$section) $section = Doctrine_Query::create()
      ->select('s.id')
      ->from('Section s, Tagging ta, Tag t')
      ->where('s.section_id = s.id')
      ->andWhere('ta.taggable_id = s.id')
      ->andWhere('ta.tag_id = t.id')
      ->andWhere('ta.taggable_model = ?', "Section")
      ->andWhere('t.name = ?', "loi:numero=".$this->numero)
      ->fetchOne();
    return $section;
  }

  public function setDossier($urldossier) {
    $this->url_an = $urldossier;
    $section = Doctrine::getTable('Section')->findOneByUrlAn($urldossier);
    if ($section) {
   # cela parait plus cohérent que les dossiers apparaissent comme récemment modifiés uniquement s'ils sont discutés et pas si un nouveau rapport vient les compléter je pense mais on peut envisager de le mettre tout de même si c utile pour solr par exemple
   #   $section->setMaxDate($this->date);
   #   $section->save();
 #print "$section->id, $this->url_an\n";
      return true;
    }
    $sections = Doctrine_Query::create()
      ->select('s.id')
      ->from('Section s, Tagging ta, Tag t')
      ->where('s.section_id = s.id')
      ->andWhere('ta.taggable_id = s.id')
      ->andWhere('ta.tag_id = t.id')
      ->andWhere('ta.taggable_model = ?', "Section")
      ->andWhere('t.name = ?', "loi:numero=".$this->numero)
      ->fetchArray();
    $res = count($sections);
    if ($res == O) {
     #print "Pas de dossier trouvé pour le texte $this->id\n";
     return false;
    } else if ($res == 1) {
      $section = Doctrine::getTable('Section')->find($sections[0]['id']);
      $section->url_an = $urldossier;
   # voir plus haut
   #  $section->setMaxDate($this->date);
      $section->save();
     #print "$section->id, $this->url_an\n";
      return true;
    } else {
     echo "$this->source : Plusieurs dossiers trouvés pour le texte $this->id de type $this->type\n";
     return false;
    }
  }

  public function setAuteurs($signataires) {    //$debug=1;
    $this->signataires = $signataires;
   //Set signatires, auteurs via PArlemnaitreTexteDocu et Organisme
    $orga = null;
    $sexe = null;
    $fonction = null;
    $signataires = preg_replace("/(Auteur|Cosignataire|Rapporteur), /", "\\1#", $signataires);
    if ($debug) echo $this->source." : ".$signataires."\n";
    $signataires = preg_split('/#/', $signataires);
    foreach ($signataires as $depute) {
      if (preg_match('/^(M[\.mle]+)/', $depute, $match)) 
        continue;
      if (preg_match('/^(.*)(\set apparentés)?\s+(Auteur|Cosignataire|Rapporteur)/', $depute, $match)) {
        $orga = trim($match[1]).$match[2];
        $organisme = Doctrine::getTable('Organisme')->findOneByNomType($orga, 'parlementaire');
        if ($organisme) {
          $this->set('Organisme', $organisme);
          $orga = $organisme->nom;
        } else {
          $groupe = Doctrine::getTable('Organisme')->findOneByNomType($orga, 'groupe');
          if ($groupe) {
            $this->set('Organisme', $groupe);
            $orga = " pour le groupe ".$orga;
          }
        }
        break;
      }
    }
    foreach ($signataires as $depute) {
      if (preg_match('/^(M[\.mle]+)\s+(.*)\s+(Auteur|Cosignataire|Rapporteur)/', $depute, $match)) {
        if (preg_match('/M[ml]/', $match[1]))
          $sexe = 'F';
        else $sexe = 'H';
        $nom = $match[2];
        $fonction = $match[3];
        if (preg_match('/^(.*)\((.*)\)/', $nom, $match)) {
          $nom = trim($match[1]);
          $circo = preg_replace('/\s/', '-', ucfirst(trim($match[2])));
        } else $circo = null;
        if (preg_match('/(ministre|[eéÉ]tat|président|haut-commissaire)/i', $nom)) {
          if ($debug) print "WARN: Skip auteur ".$nom." for ".$this->source."\n";
          continue;
        }
        $nom = ucfirst($nom);
        if ($debug) echo $nom."//".$sexe."//".$orga."//".$circo."//".$fonction." => ";
        $depute = Doctrine::getTable('Parlementaire')->findOneByNomSexeGroupeCirco($nom, $sexe, null, $circo, $this);
        if (!$depute) print "WARNING: Auteur introuvable in ".$this->source." : ".$nom." // ".$sexe." // ".$orga."//".$fonction."\n";
        else {
          if ($debug) echo $depute->nom."\n";
          $this->addParlementaire($depute, $fonction, $orga);
          $depute->free();
        }
      }
    }
  }

  public function addParlementaire($depute, $fonction, $organisme = 0) {
    foreach(Doctrine::getTable('ParlementaireTexteloi')->createQuery('pa')->select('parlementaire_id')->where('texteloi_id = ?', $this->id)->fetchArray() as $parldt) if ($parldt['parlementaire_id'] == $depute->id) return true;

    $pd = new ParlementaireTexteloi();
    $pd->_set('Parlementaire', $depute);
    $pd->_set('Texteloi', $this);
    if ($fonction === "Auteur")
      $pd->_set('importance', 1);
    else if ($fonction === "Rapporteur") 
      $pd->_set('importance', 3);
    else if ($fonction === "Cosignataire")
      $pd->_set('importance', 5);
    if ($organisme && $fonction != "Cosignataire") {
      if (!(preg_match('/^ pour le groupe/', $organisme))) {
        $fonction .= " pour l";
        if (preg_match('/^[aeiouyh]/i', $organisme))
          $fonction .= "'";
        else if (preg_match('/^comit/i', $organisme))
          $fonction .= "e ";
        else $fonction .= "a ";
      }
      $fonction .= $organisme;
    }
    $pd->_set('fonction', $fonction);
    if ($pd->save()) {
      $pd->free();
      return true;
    } else return false;
  }

  public function getTypeString() {
    $str = "ce";
    if (preg_match('/(propos|lettre)/', $this->type))
      $str .= "tte";
    $str .= " ".strtolower($this->type);
    return $str;
  }

  public function getAuteursString() {
    if ($this->type === "Texte de la commission")
      return $this->signataires;
    return $this->signataires;
  }

  public function getCommission() {
    if ($this->type === "Texte de la commission") {
      $rap = Doctrine::getTable('Texteloi')->find("$this->numero");
      return $rap->getOrganisme();
    }
    return $this->getOrganisme();
  }

  public function getTitreComplet() {
    $str = "";
    if ($this->annexe && preg_match('/a/', $this->id)) {
      $str .= "Annexe N°&nbsp;".$annexe." ";
      if ($this->type === "Avis")
        $str .= "à l'";
      else $str .=  "au ";
    }
    $str .= $this->type;
    if (!preg_match('/^,/', $this->type_details))
      $str .= " ";
    $str .= $this->type_details;
    if (!preg_match('/^,/', $this->titre))
      $str .=  " ";
    $str .= $this->titre;
    if ($this->annexe && preg_match('/t/', $this->id))
      $str .= " (Tome $annexe)";
    return $str;
  }
}
