<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TitreLoiTable extends Doctrine_Table
{

  public function findLightLoi($id) {
    $loiarr = Doctrine_Query::create()
      ->select('t.titre, t.nb_articles, t.id')
      ->from('TitreLoi t')
      ->where('t.texteloi_id = ?', $id)
      ->andWhere('t.leveltype = ?', 'loi')
      ->fetchOne();
    if (!$loiarr) return null;
    else {
       $loi = new TitreLoi();
       $loi->titre = $loiarr['titre'];
       $loi->nb_articles = $loiarr['nb_articles'];
       $loi->texteloi_id = $id;
       $loi->id = $loiarr['id'];
       return $loi;
    }
  }

  public function findLoi($numero) {
    $query = $this->createQuery('t')
      ->where('t.texteloi_id = ?', $numero)
      ->andWhere('t.leveltype = ?', 'loi');
    return $query->fetchOne();
  }

  public function findLoiOrCreate($numero) {
    $loi = $this->findLoi($numero);
    if (!$loi) {
      $loi = new TitreLoi();
      $loi->texteloi_id = $numero;
      $loi->nb_articles = 0;
      $loi->leveltype = 'loi';
      $loi->save();
    }
    $loi->titre_loi_id = $loi->id;
    $loi->save();
    return $loi;
  }

  public function identifyAndFindLevel($loi, $levels = array(0, 0, 0, 0)) {
    return self::findLevel($loi, TitreLoi::findLevel($levels), $levels);
  }

  public function findLevel($loi, $level, $levels = array(0, 0, 0, 0)) {
    $query = $this->createQuery('t')
      ->where('t.texteloi_id = ?', $loi);
    for ($i = 0; $i < 4; $i++) {
      if ($i < $level)
        $query->andWhere('t.level'.($i+1).' = ?', $levels[$i]);
      else $query->andWhere('t.level'.($i+1).' IS NULL');
    }
    return $query->fetchOne();
  }

  public function findLevelOrCreate($loi, $level, $levels = array(0, 0, 0, 0), $leveltype = '') {
    if ($level == 0)
      return $this->findLoiOrCreate($loi);
    $sect = $this->findLevel($loi, $level, $levels);
    if (!$sect) {
      $sect =  new TitreLoi();
      $sect->texteloi_id = $loi;
      for ($i = 0; $i < $level; $i++) 
        $sect->setLevel($i+1, $levels[$i]);
      $sect->nb_articles = 0;
    }
    if (!$sect->leveltype && $leveltype != "")
      $sect->leveltype = $leveltype;
    $sect->titre_loi_id = $this->findLevelOrCreate($loi, $level-1, $levels)->id;
    $sect->save();
    return $sect;
  }


}
