<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ParlementaireTable extends PersonnaliteTable
{

  public function getPager($request, $query = NULL)
  {
    $pager = new sfDoctrinePager('Parlementaire',20);
    if (!$query) {
      $query = $this->createQuery('p')->orderBy('p.nom_de_famille ASC');
    }
    $pager->setQuery($query);
    $pager->setPage($request->getParameter('page', 1));
    $pager->init();
    return $pager;
  }
}