perl parse_metas.pl rap/http:__www.assemblee-nationale.fr_13_europe_rap-info_i0404.asp > out/http:__www.assemblee-nationale.fr_13_europe_rap-info_i0404.asp
perl parse_metas.pl rap/http:__www.assemblee-nationale.fr_13_europe_rap-info_i0440.asp > out/http:__www.assemblee-nationale.fr_13_europe_rap-info_i0440.asp
perl parse_metas.pl rap/http:__www.assemblee-nationale.fr_13_europe_rap-info_i1124.asp > out/http:__www.assemblee-nationale.fr_13_europe_rap-info_i1124.asp
perl parse_metas.pl ppr/http:__www.assemblee-nationale.fr_13_europe_resolutions_ppe0405.asp > out/http:__www.assemblee-nationale.fr_13_europe_resolutions_ppe0405.asp
perl parse_metas.pl ppr/http:__www.assemblee-nationale.fr_13_europe_resolutions_ppe0441.asp > out/http:__www.assemblee-nationale.fr_13_europe_resolutions_ppe0441.asp
perl parse_metas.pl ppr/http:__www.assemblee-nationale.fr_13_europe_resolutions_ppe0887.asp > out/http:__www.assemblee-nationale.fr_13_europe_resolutions_ppe0887.asp
perl parse_metas.pl pjl/http:__www.assemblee-nationale.fr_13_projets_pl0012.asp > out/http:__www.assemblee-nationale.fr_13_projets_pl0012.asp
perl parse_metas.pl pjl/http:__www.assemblee-nationale.fr_13_projets_pl0015.asp > out/http:__www.assemblee-nationale.fr_13_projets_pl0015.asp
perl parse_metas.pl pjl/http:__www.assemblee-nationale.fr_13_projets_pl0021.asp > out/http:__www.assemblee-nationale.fr_13_projets_pl0021.asp
perl parse_metas.pl pjl/http:__www.assemblee-nationale.fr_13_projets_pl0117.asp > out/http:__www.assemblee-nationale.fr_13_projets_pl0117.asp
perl parse_metas.pl pjl/http:__www.assemblee-nationale.fr_13_projets_pl0121.asp > out/http:__www.assemblee-nationale.fr_13_projets_pl0121.asp
perl parse_metas.pl pjl/http:__www.assemblee-nationale.fr_13_projets_pl0153.asp > out/http:__www.assemblee-nationale.fr_13_projets_pl0153.asp
perl parse_metas.pl pjl/http:__www.assemblee-nationale.fr_13_projets_pl0154.asp > out/http:__www.assemblee-nationale.fr_13_projets_pl0154.asp
perl parse_metas.pl pjl/http:__www.assemblee-nationale.fr_13_projets_pl0159.asp > out/http:__www.assemblee-nationale.fr_13_projets_pl0159.asp
perl parse_metas.pl pjl/http:__www.assemblee-nationale.fr_13_projets_pl0249.asp > out/http:__www.assemblee-nationale.fr_13_projets_pl0249.asp
perl parse_metas.pl pjl/http:__www.assemblee-nationale.fr_13_projets_pl0344.asp > out/http:__www.assemblee-nationale.fr_13_projets_pl0344.asp
perl parse_metas.pl pjl/http:__www.assemblee-nationale.fr_13_projets_pl0353.asp > out/http:__www.assemblee-nationale.fr_13_projets_pl0353.asp
perl parse_metas.pl pjl/http:__www.assemblee-nationale.fr_13_projets_pl0519.asp > out/http:__www.assemblee-nationale.fr_13_projets_pl0519.asp
perl parse_metas.pl pjl/http:__www.assemblee-nationale.fr_13_projets_pl0520.asp > out/http:__www.assemblee-nationale.fr_13_projets_pl0520.asp
perl parse_metas.pl pjl/http:__www.assemblee-nationale.fr_13_projets_pl0767.asp > out/http:__www.assemblee-nationale.fr_13_projets_pl0767.asp
perl parse_metas.pl pjl/http:__www.assemblee-nationale.fr_13_projets_pl0893.asp > out/http:__www.assemblee-nationale.fr_13_projets_pl0893.asp
perl parse_metas.pl ppl/http:__www.assemblee-nationale.fr_13_propositions_pion0150.asp > out/http:__www.assemblee-nationale.fr_13_propositions_pion0150.asp
perl parse_metas.pl ppl/http:__www.assemblee-nationale.fr_13_propositions_pion0242.asp > out/http:__www.assemblee-nationale.fr_13_propositions_pion0242.asp
perl parse_metas.pl ppl/http:__www.assemblee-nationale.fr_13_propositions_pion0288.asp > out/http:__www.assemblee-nationale.fr_13_propositions_pion0288.asp
perl parse_metas.pl ppl/http:__www.assemblee-nationale.fr_13_propositions_pion0289.asp > out/http:__www.assemblee-nationale.fr_13_propositions_pion0289.asp
perl parse_metas.pl ppl/http:__www.assemblee-nationale.fr_13_propositions_pion0290.asp > out/http:__www.assemblee-nationale.fr_13_propositions_pion0290.asp
perl parse_metas.pl ppl/http:__www.assemblee-nationale.fr_13_propositions_pion0297.asp > out/http:__www.assemblee-nationale.fr_13_propositions_pion0297.asp
perl parse_metas.pl ppl/http:__www.assemblee-nationale.fr_13_propositions_pion0298.asp > out/http:__www.assemblee-nationale.fr_13_propositions_pion0298.asp
perl parse_metas.pl ppl/http:__www.assemblee-nationale.fr_13_propositions_pion0345.asp > out/http:__www.assemblee-nationale.fr_13_propositions_pion0345.asp
perl parse_metas.pl ppl/http:__www.assemblee-nationale.fr_13_propositions_pion0347.asp > out/http:__www.assemblee-nationale.fr_13_propositions_pion0347.asp
perl parse_metas.pl ppl/http:__www.assemblee-nationale.fr_13_propositions_pion0399.asp > out/http:__www.assemblee-nationale.fr_13_propositions_pion0399.asp
perl parse_metas.pl ppl/http:__www.assemblee-nationale.fr_13_propositions_pion0409.asp > out/http:__www.assemblee-nationale.fr_13_propositions_pion0409.asp
perl parse_metas.pl ppl/http:__www.assemblee-nationale.fr_13_propositions_pion0413.asp > out/http:__www.assemblee-nationale.fr_13_propositions_pion0413.asp
perl parse_metas.pl ppl/http:__www.assemblee-nationale.fr_13_propositions_pion0414.asp > out/http:__www.assemblee-nationale.fr_13_propositions_pion0414.asp
perl parse_metas.pl ppl/http:__www.assemblee-nationale.fr_13_propositions_pion1064.asp > out/http:__www.assemblee-nationale.fr_13_propositions_pion1064.asp
perl parse_metas.pl ppl/http:__www.assemblee-nationale.fr_13_propositions_pion1098.asp > out/http:__www.assemblee-nationale.fr_13_propositions_pion1098.asp
perl parse_metas.pl rap/http:__www.assemblee-nationale.fr_13_rapports_r0077.asp > out/http:__www.assemblee-nationale.fr_13_rapports_r0077.asp
perl parse_metas.pl rap/http:__www.assemblee-nationale.fr_13_rapports_r0098.asp > out/http:__www.assemblee-nationale.fr_13_rapports_r0098.asp
perl parse_metas.pl rap/http:__www.assemblee-nationale.fr_13_rapports_r0157.asp > out/http:__www.assemblee-nationale.fr_13_rapports_r0157.asp
perl parse_metas.pl rap/http:__www.assemblee-nationale.fr_13_rapports_r0163.asp > out/http:__www.assemblee-nationale.fr_13_rapports_r0163.asp
perl parse_metas.pl rap/http:__www.assemblee-nationale.fr_13_rapports_r0273.asp > out/http:__www.assemblee-nationale.fr_13_rapports_r0273.asp
perl parse_metas.pl rap/http:__www.assemblee-nationale.fr_13_rapports_r0437.asp > out/http:__www.assemblee-nationale.fr_13_rapports_r0437.asp
perl parse_metas.pl rap/http:__www.assemblee-nationale.fr_13_rapports_r0438.asp > out/http:__www.assemblee-nationale.fr_13_rapports_r0438.asp
perl parse_metas.pl rap/http:__www.assemblee-nationale.fr_13_rapports_r0492.asp > out/http:__www.assemblee-nationale.fr_13_rapports_r0492.asp
perl parse_metas.pl rap/http:__www.assemblee-nationale.fr_13_rapports_r0509.asp > out/http:__www.assemblee-nationale.fr_13_rapports_r0509.asp
perl parse_metas.pl rap/http:__www.assemblee-nationale.fr_13_rapports_r0604.asp > out/http:__www.assemblee-nationale.fr_13_rapports_r0604.asp
perl parse_metas.pl rap/http:__www.assemblee-nationale.fr_13_rapports_r0605.asp > out/http:__www.assemblee-nationale.fr_13_rapports_r0605.asp
perl parse_metas.pl rap/http:__www.assemblee-nationale.fr_13_rapports_r0685.asp > out/http:__www.assemblee-nationale.fr_13_rapports_r0685.asp
perl parse_metas.pl rap/http:__www.assemblee-nationale.fr_13_rapports_r0777.asp > out/http:__www.assemblee-nationale.fr_13_rapports_r0777.asp
perl parse_metas.pl rap/http:__www.assemblee-nationale.fr_13_rapports_r0912.asp > out/http:__www.assemblee-nationale.fr_13_rapports_r0912.asp
perl parse_metas.pl rap/http:__www.assemblee-nationale.fr_13_rapports_r0915.asp > out/http:__www.assemblee-nationale.fr_13_rapports_r0915.asp
perl parse_metas.pl rap/http:__www.assemblee-nationale.fr_13_rapports_r0949.asp > out/http:__www.assemblee-nationale.fr_13_rapports_r0949.asp
perl parse_metas.pl rap/http:__www.assemblee-nationale.fr_13_rapports_r1160.asp > out/http:__www.assemblee-nationale.fr_13_rapports_r1160.asp
perl parse_metas.pl rap/http:__www.assemblee-nationale.fr_13_rapports_r1444.asp > out/http:__www.assemblee-nationale.fr_13_rapports_r1444.asp
